From plasticschandra@yahoo.co.in Wed Dec 15 08:50:05 2010
Return-Path: <plasticschandra@yahoo.co.in>
X-Sender: plasticschandra@yahoo.co.in
X-Apparently-To: ponniyinselvan@yahoogroups.com
X-Received: (qmail 74606 invoked from network); 15 Dec 2010 16:50:03 -0000
X-Received: from unknown (98.137.34.45)
  by m1.grp.sp2.yahoo.com with QMQP; 15 Dec 2010 16:50:03 -0000
X-Received: from unknown (HELO web137302.mail.in.yahoo.com) (121.101.151.129)
  by mta2.grp.sp2.yahoo.com with SMTP; 15 Dec 2010 16:49:10 -0000
X-Received: (qmail 30926 invoked by uid 60001); 15 Dec 2010 16:49:09 -0000
Message-ID: <128724.28079.qm@web137302.mail.in.yahoo.com>
X-YMail-OSG: IbyoH3MVM1mWaFMYx7CFQk1JTb6mf3Ln7ys4Hd4H.1saCM8
 yOClL065y5O0BQpusnYupkgCPIjwW5YWA6Ds0yN0QnRmuzwqAycYqnCqMwC3
 KRe9vtXDxHcQir3q.mAitZLnz5GlPcUF76l1uF520H0Lbouyf.ZnrHmB3mpS
 xma0AsV.ygxRsi6jMlHIQ9x17IFe0PlcdaqvPn0AqzTavKUZaGrLXD.c3mh1
 llQZRdHMrzc0NjRP8b7RpPSe3QvUaCGphd1F6WIY3c875ln4SP7_fwLd.Ihp
 Jou_lSMCsoJdSOHFVRg--
X-Received: from [122.164.167.10] by web137302.mail.in.yahoo.com via HTTP; Wed, 15 Dec 2010 22:19:04 IST
X-Mailer: YahooMailRC/553 YahooMailWebService/0.8.107.285259
Date: Wed, 15 Dec 2010 22:19:03 +0530 (IST)
To: temple_cleaners@yahoogroups.com, ponniyinselvan@yahoogroups.com
Cc: satyamurthy t <tsmrty@yahoo.com>
MIME-Version: 1.0
Content-Type: multipart/mixed; boundary="0-372223162-1292431744=:28079"
X-Originating-IP: 121.101.151.129
X-eGroups-Msg-Info: 1:5:0:0:0
From: J Chandrasekaran <plasticschandra@yahoo.co.in>
Subject: Fw: Story on art restorers
X-Yahoo-Group-Post: member; u=278138984; y=c1AYL_jUwu8FZQ6uisp4zG1Tqyct9oR2UB_EMjQgZzu_2lA4TP79vxET
X-Yahoo-Profile: plasticschandra


           
--0-372223162-1292431744=:28079
 
Content-Type: multipart/alternative; boundary="0-557730478-1292431744=:28079"


           
--0-557730478-1292431744=:28079
 
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable


Lakshmy Venkiteswaran has done a good article on need for having conservati=
on of=20
antiques in her article in Indian Express - Express buzz.


She sent this:

Attached is the PDF copy of my story on art restorers. If the attachment do=
esn't=20
open, you can see the text version in the following=20
link:http://expressbuzz.com/education/knights-of-the-arts/228201.html.=20

REACH thanks Ms. Lakshmy for her timely article.

Chandra


           
--0-557730478-1292431744=:28079
 
Content-Type: text/html; charset=utf-8
Content-Transfer-Encoding: quoted-printable


<html><head><style type=3D"text/css"><!-- DIV {margin:0px;} --></style></he=
ad><body><div style=3D"font-family:verdana, helvetica, sans-serif;font-size=
:8pt"><div></div><div><span class=3D"Apple-style-span" style=3D"font-family=
: 'times new roman', 'new york', times, serif; font-size: 16px; ">Lakshmy V=
enkiteswaran has done a good article on need for having conservation of ant=
iques in her article in Indian Express - Express buzz.</span></div><div><di=
v style=3D"font-family:verdana, helvetica, sans-serif;font-size:8pt"><div s=
tyle=3D"font-family:times new roman, new york, times, serif;font-size:12pt"=
><div class=3D"gmail_quote"><div class=3D"gmail_quote">
<div><br></div><div>She sent this:</div><div><br></div><div>Attached is the=
 PDF copy of my story on art restorers. If the attachment doesn't open, you=
 can see the text version in the following link:</div><a rel=3D"nofollow" t=
arget=3D"_blank" href=3D"http://expressbuzz.com/education/knights-of-the-ar=
ts/228201.html">http://expressbuzz.com/education/knights-of-the-arts/228201=
.html</a>.&nbsp;</div>
<div class=3D"gmail_quote"><br></div><div class=3D"gmail_quote">REACH thank=
s Ms. Lakshmy for her timely article.</div><div class=3D"gmail_quote"><br><=
/div><div class=3D"gmail_quote">Chandra</div></div>
</div></div></div><div style=3D"position:fixed"></div>


</div><br></body></html>
           
--0-557730478-1292431744=:28079--
--0-372223162-1292431744=:28079
 
Content-Type: application/pdf; name=Art
Content-Transfer-Encoding: base64
Content-Disposition: attachment; filename="Art Restorers Dec 6 2010.pdf"


[Attachment content not displayed.]

           
--0-372223162-1292431744=:28079-