                                                                                                                                                                                                                                                               
Delivered-To: ygroup@ponniyinselvan.in
Received: by 10.141.12.16 with SMTP id p16cs204988rvi;
        Fri, 6 Nov 2009 03:34:55 -0800 (PST)
Received: by 10.150.44.3 with SMTP id r3mr7510976ybr.241.1257507293936;
        Fri, 06 Nov 2009 03:34:53 -0800 (PST)
Return-Path: <sentto-6248931-35340-1257507290-ygroup=ponniyinselvan.in@returns.groups.yahoo.com>
Received: from n78d.bullet.mail.sp1.yahoo.com (n78d.bullet.mail.sp1.yahoo.com [98.136.45.103])
        by mx.google.com with SMTP id 21si6045373gxk.25.2009.11.06.03.34.52;
        Fri, 06 Nov 2009 03:34:52 -0800 (PST)
Received-SPF: pass (google.com: domain of sentto-6248931-35340-1257507290-ygroup=ponniyinselvan.in@returns.groups.yahoo.com designates 98.136.45.103 as permitted sender) client-ip=98.136.45.103;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of sentto-6248931-35340-1257507290-ygroup=ponniyinselvan.in@returns.groups.yahoo.com designates 98.136.45.103 as permitted sender) smtp.mail=sentto-6248931-35340-1257507290-ygroup=ponniyinselvan.in@returns.groups.yahoo.com; dkim=pass header.i=@yahoogroups.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yahoogroups.com; s=lima; t=1257507291; bh=8nIvz54cH4zRxjYeK1KwF1LSpNzSAfWvFTbgAIBCHsM=; h=Received:Received:X-Yahoo-Newman-Id:X-Sender:X-Apparently-To:X-Received:X-Received:X-Received:X-Received:X-Received:To:Message-ID:In-Reply-To:User-Agent:X-Mailer:X-Originating-IP:X-eGroups-Msg-Info:X-Yahoo-Post-IP:From:X-Yahoo-Profile:Sender:MIME-Version:Mailing-List:Delivered-To:List-Id:Precedence:List-Unsubscribe:Date:Subject:Reply-To:X-Yahoo-Newman-Property:Content-Type; b=pxrxtmW93lkAcRo46cyctm0ErVdphQOlQaTlgWnD1qDR+wnyV683Y5Va82rCSriJHkdkmJFE5/fE7gusR2KAzpIRFBOjqlNT61kLnjhF1xZ/x9Yi0fW4wJOSPkbCLXIp
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws; s=lima; d=yahoogroups.com;
	b=lRV2yLPOMNMlVK7ucgmPJ3doO/WVgvkV88LAXev6Wk4aFftfXenYQqPtaEeGadXRRvoeKbmPE1u0Fl7Qs49Z3D6CD2PnkZnUz8H4/kdcDGVzbxqKHz0Sp+zH+6nFXFR3;
Received: from [69.147.65.147] by n78.bullet.mail.sp1.yahoo.com with NNFMP; 06 Nov 2009 11:34:51 -0000
Received: from [98.137.34.37] by t10.bullet.mail.sp1.yahoo.com with NNFMP; 06 Nov 2009 11:34:51 -0000
X-Yahoo-Newman-Id: 6248931-m35340
X-Sender: sampath_srinivasaraghavan@yahoo.co.in
X-Apparently-To: ponniyinselvan@yahoogroups.com
X-Received: (qmail 60365 invoked from network); 6 Nov 2009 11:34:49 -0000
X-Received: from unknown (98.137.34.44)
  by m1.grp.sp2.yahoo.com with QMQP; 6 Nov 2009 11:34:49 -0000
X-Received: from unknown (HELO n38b.bullet.mail.sp1.yahoo.com) (66.163.168.152)
  by mta1.grp.sp2.yahoo.com with SMTP; 6 Nov 2009 11:34:49 -0000
X-Received: from [69.147.65.174] by n38.bullet.mail.sp1.yahoo.com with NNFMP; 06 Nov 2009 11:34:35 -0000
X-Received: from [98.137.34.72] by t12.bullet.mail.sp1.yahoo.com with NNFMP; 06 Nov 2009 11:34:35 -0000
To: ponniyinselvan@yahoogroups.com
Message-ID: <hd11kb+r45o@eGroups.com>
In-Reply-To: <96ab1a490911052247m40758d27na483c2a3f8e97959@mail.gmail.com>
User-Agent: eGroups-EW/0.82
X-Mailer: Yahoo Groups Message Poster
X-Originating-IP: 66.163.168.152
X-eGroups-Msg-Info: 1:6:0:0:0
X-Yahoo-Post-IP: 115.109.15.87
From: "ssampath108" <sampath_srinivasaraghavan@yahoo.co.in>
X-Yahoo-Profile: ssampath108
Sender: ponniyinselvan@yahoogroups.com
MIME-Version: 1.0
Mailing-List: list ponniyinselvan@yahoogroups.com; contact ponniyinselvan-owner@yahoogroups.com
Delivered-To: mailing list ponniyinselvan@yahoogroups.com
List-Id: <ponniyinselvan.yahoogroups.com>
Precedence: bulk
List-Unsubscribe: <mailto:ponniyinselvan-unsubscribe@yahoogroups.com>
Date: Fri, 06 Nov 2009 11:34:35 -0000
Subject: [ponniyinselvan] =?iso-8859-1?B?UmU6IEZ3ZDogW1BvZXRyeSBJbiBTdG9uZXzgrpXg?=
 =?iso-8859-1?B?rrLgr43grrLgrr/grrLgr4cg4K6V4K6y4K+I4K61?=
 =?iso-8859-1?B?4K6j4K+N4K6j4K6u4K+NIOCuleCuo+CvjeCun+Cv?=
 =?iso-8859-1?B?i+CuruCvjV0gVGhlIG1vYXQgYXJvdW5kIHRoZSBU?=
 =?iso-8859-1?B?YW5qb3JlIEJpZyB0ZW1wbGUgfCDgrqTgrp7gr43g?=
 =?iso-8859-1?B?rprgr4gg4K6q4K+G4K6w4K6/4K6vIOCuleCvi+Cu?=
 =?iso-8859-1?B?r+Cuv+CusuCvjSDgroXgrpXgrrTgrr8=?=
Reply-To: ponniyinselvan@yahoogroups.com
X-Yahoo-Newman-Property: groups-email-ff-m
Content-Type: multipart/alternative;
 boundary="kxFkv1tbrjBYnsxZexqtqb0QKPyrVloqsV0vnu4"

--kxFkv1tbrjBYnsxZexqtqb0QKPyrVloqsV0vnu4
Content-Type: text/plain; charset=ISO-8859-1
Content-Transfer-Encoding: base64

SGkgVmlqYXksCgpOaWNlIGFuZCBpbnRlcmVzdGluZy4gWW91IGhhdmUgYSBzaGFycCBleWUg
Zm9yIGRldGFpbHMgYW5kIG15c3Rlcmllcy4KUGVyaGFwcywgZHVyaW5nIHJlbm92YXRpb24g
aW4gdGhlIDIwdGggY2VudHVyeSwgdGhlIHNjdWxwdHVyZSB3YXMKcmVtb3ZlZCBhbmQgdGhl
biBmb3Jnb3R0ZW4uIExldCB1cyBob3BlIGl0IGlzIHNhZmUgaW4gYSBtdXNldW0uCgpJIGhh
dmUgYSBkb3VidC4gTm9ybWFsbHksIG9ubHkgZm9ydHMgYW5kIHBhbGFjZXMgaGF2ZSBtb2F0
cyBhcyBhIGJhcnJpZXIKYWdhaW5zdCBhdHRhY2tzLiBXaHkgZm9yIGEgdGVtcGxlPyBBcmUg
dGhlcmUgb3RoZXIgdGVtcGxlcyB3aXRoIG1vdHM/IEkKYW0gbm90IGF3YXJlIG9mIGFueS4K
U2FtcGF0aAoKCi0tLSBJbiBwb25uaXlpbnNlbHZhbkB5YWhvb2dyb3Vwcy5jb20sIHZqIGt1
bWFyIDx2ai5lcGlzdGVtZUAuLi4+IHdyb3RlOgo+Cj4gUG9ldHJ5IEluIFN0b25lfOCuleCu
suCvjeCusuCuv+CusuCvhwrgrpXgrrLgr4jgrrXgrqPgr43grqPgrq7gr40KPiDgrpXgrqPg
r43grp/gr4vgrq7gr40gaGFzIHBvc3RlZCBhIG5ldyBpdGVtLCAnVGhlIG1vYXQgYXJvdW5k
CnRoZSBUYW5qb3JlIEJpZwo+IHRlbXBsZSB8IOCupOCunuCvjeCumuCviCDgrqrgr4bgrrDg
rr/grq8K4K6V4K+L4K6v4K6/4K6y4K+NIOCuheCuleCutOCuvyAnCj4KPiBbbGFuZ19lbl0K
Pgo+IFRoZSByZWNlbnQgaGVhZGxpbmVzIGZvciByZW5vdmF0aW9uIG9mIHRoZSBtb2F0IGFy
b3VuZCB0aGUgQmlnIHRlbXBsZQppbgo+IHRhbmpvcmUsCj4gQVNJIHN1Ym1pdHMgUnMuMS1j
cm9yZSBwcm9wb3NhbCB0byByZW5vdmF0ZSBtb2F0IGFyb3VuZCBCaWcgVGVtcGxlICwKdG9v
ayBtZQo+IGJhY2sgc29tZSB5ZWFycyBhZ28gLSB3aGVuIGkgaGFkIGNoYW5jZWQgb24gYSB2
ZXJ5IGludGVyZXN0aW5nIGFudGlxdWUKPiBwaG90b2dyYXBoIGZyb20gdGhlIGFyY2hpdmVz
IG9mIHRoZSBCcml0aXNoIExpYnJhcnkuCj4KPiBUaGUgYXJjaGl2ZXMgYXJlIGEgcmVhbCB0
cmVhc3VyZSBbLi4uXQo+Cj4gWW91IG1heSB2aWV3IHRoZSBsYXRlc3QgcG9zdCBhdAo+Cmh0
dHA6Ly93d3cucG9ldHJ5aW5zdG9uZS5pbi8yMDA5LzExLzA2L3RoZS1tb2F0LWFyb3VuZC10
aGUtdGFuam9yZS1iaWctdFwKZW1wbGUuaHRtbAo+Cj4g4K6k4K6e4K+N4K6a4K+IIOCuquCv
huCusOCuv+CuryDgrpXgr4vgrq/grr/grrLgr40KPgrgroXgrpXgrrTgrr88aHR0cDovL3d3
dy5wb2V0cnlpbnN0b25lLmluL2xhbmcvdGEvMjAwOS8xMS8wNi90aGUtbW9hXAp0LWFyb3Vu
ZC10aGUtdGFuam9yZS1iaWctdGVtcGxlLmh0bWw+Cj4KPiA8aHR0cDovL3d3dy5wb2V0cnlp
bnN0b25lLmluL3dwLWFkbWluL3Bvc3QucGhwP2FjdGlvbj1lZGl0JnBvc3Q9MjcyMD4KPgo+
IOCumuCuruCvgOCuquCupOCvjeCupOCuv+Curwrgrqjgrr7grrPgr4fgrp/gr43grp/grr/g
rrLgr40g4K6k4K+K4K6y4K+N4K6y4K6/4K6v4K6y4K+NCuCupOCvgeCuseCviCDgrifgrrDg
r4Eg4K6V4K+L4K6f4K6/CuCusOCvgeCuquCuvuCur+CvjSDgrprgr4bgrrLgrrXgrr/grrLg
r40K4K6k4K6e4K+N4K6a4K+IIOCuquCvhuCusOCuv+Curwo+IOCuleCvi+Cur+Cuv+CusuCv
jSDgroXgrpXgrrTgrr/grq/gr4gK4K6a4K+G4K6q4K+N4K6q4K6p4K6/4K6f4K6q4K+NIOCu
quCvi+CuleCuv+CuseCupOCvgQrgro7grqngr43grrEg4K6a4K+G4K6v4K+N4K6k4K6/CuCu
teCuvuCumuCuv+CupOCvjeCupOCvgSDgrq7grpXgrr/grrTgr43grqjgr43grqTgr4fgrqng
r40KPgrgrprgr4bgrq/gr43grqTgrr88aHR0cDovL3d3dy5oaW5kdS5jb20vMjAwOS8xMS8w
NS9zdG9yaWVzLzIwMDkxMTBcCjU1ODEyMDEwMC5odG0+LuCuieCun+CuqeCvhwo+IOCuqOCu
v+CuqeCviOCuteCvgSDgrprgrr/grrIK4K6G4K6j4K+N4K6f4K+B4K6V4K6z4K+B4K6V4K+N
4K6V4K+BCuCuruCvgeCuqeCvjeCuqeCusOCvjSDgrqrgrr/grrDgrr/grp/gr43grp/grr/g
rrfgr40K4K6V4K6w4K+B4K614K+C4K6y4K6k4K+N4K6k4K6/4K6y4K+NIOCuieCus+CvjeCu
swrgrprgrr/grrIg4K6u4K6/4K6VIOCuheCusOCuv+Curwo+IOCuquCvgeCuleCviOCuquCv
jeCuquCun+CumeCvjeCuleCus+CviOCuquCvjQrgrqrgrr7grrDgr43grrXgr4jgrq/grr/g
rp/gr43grp/grqTgr4Hgrq7gr40uCuCuheCupOCuv+CusuCvgeCuruCvjQrgrpXgr4HgrrHg
rr/grqrgr43grqrgrr/grp/gr4Hgrq7gr40g4K6q4K6f4K6/4K6v4K6+4K6VCuCuJ+CusOCv
gSDgrqrgrp/grq7gr4Hgrq7gr40hISEKPgo+Cj4KaHR0cDovL3d3dy5wb2V0cnlpbnN0b25l
LmluL2xhbmcvdGEvMjAwOS8xMS8wNi90aGUtbW9hdC1hcm91bmQtdGhlLXRhbmpvXApyZS1i
aWctdGVtcGxlLmh0bWwKPgo+Cj4gQmVzdCByZWdhcmRzLAo+IFZpamF5Cj4gdmouZXBpc3Rl
bWVALi4uCj4K

--kxFkv1tbrjBYnsxZexqtqb0QKPyrVloqsV0vnu4
Content-Type: text/html; charset=ISO-8859-1
Content-Transfer-Encoding: quoted-printable




<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/htm=
l4/strict.dtd">
<html>
<head>
</head>







<body style=3D"background-color: #fff;">
<span style=3D"display:none">&nbsp;</span>

<!--~-|**|PrettyHtmlStartT|**|-~-->
<div id=3D"ygrp-mlmsg" style=3D"position:relative;">
  <div id=3D"ygrp-msg" style=3D"z-index: 1;">
<!--~-|**|PrettyHtmlEndT|**|-~-->

    <div id=3D"ygrp-text" >
=20=20=20=20=20=20
=20=20=20=20=20=20
      <p>Hi Vijay,<br>
<br>
Nice and interesting. You have a sharp eye for details and mysteries.<br>
Perhaps, during renovation in the 20th century, the sculpture was<br>
removed and then forgotten. Let us hope it is safe in a museum.<br>
<br>
I have a doubt. Normally, only forts and palaces have moats as a barrier<br=
>
against attacks. Why for a temple? Are there other temples with mots? I<br>
am not aware of any.<br>
Sampath<br>
<br>
--- In <a href=3D"mailto:ponniyinselvan%40yahoogroups.com">ponniyinselvan@<=
wbr>yahoogroups.<wbr>com</a>, vj kumar &lt;vj.episteme@<wbr>...&gt; wrote:<=
br>
&gt;<br>
&gt; Poetry In Stone|=E0=AE=95=E0=AE=B2=E0=AF=8D=E0=AE=B2=E0=AE=BF=E0=AE=B2=
=E0=AF=87<br>
=E0=AE=95=E0=AE=B2=E0=AF=88=E0=AE=B5=E0=AE=A3=E0=AF=8D=E0=AE=A3=E0=AE=AE=E0=
=AF=8D<br>
&gt; =E0=AE=95=E0=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=8B=E0=AE=AE=E0=AF=8D has po=
sted a new item, 'The moat around<br>
the Tanjore Big<br>
&gt; temple | =E0=AE=A4=E0=AE=9E=E0=AF=8D=E0=AE=9A=E0=AF=88 =E0=AE=AA=E0=AF=
=86=E0=AE=B0=E0=AE=BF=E0=AE=AF<br>
=E0=AE=95=E0=AF=8B=E0=AE=AF=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=85=E0=AE=95=
=E0=AE=B4=E0=AE=BF '<br>
&gt;<br>
&gt; [lang_en]<br>
&gt;<br>
&gt; The recent headlines for renovation of the moat around the Big temple<=
br>
in<br>
&gt; tanjore,<br>
&gt; ASI submits Rs.1-crore proposal to renovate moat around Big Temple ,<b=
r>
took me<br>
&gt; back some years ago - when i had chanced on a very interesting antique=
<br>
&gt; photograph from the archives of the British Library.<br>
&gt;<br>
&gt; The archives are a real treasure [...]<br>
&gt;<br>
&gt; You may view the latest post at<br>
&gt;<br>
<a href=3D"http://www.poetryinstone.in/2009/11/06/the-moat-around-the-tanjo=
re-big-temple.html">http://www.poetryin<wbr>stone.in/<wbr>2009/11/06/<wbr>t=
he-moat-<wbr>around-the-<wbr>tanjore-big-<wbr>t\<br>
emple.html</a><br>
&gt;<br>
&gt; =E0=AE=A4=E0=AE=9E=E0=AF=8D=E0=AE=9A=E0=AF=88 =E0=AE=AA=E0=AF=86=E0=AE=
=B0=E0=AE=BF=E0=AE=AF =E0=AE=95=E0=AF=8B=E0=AE=AF=E0=AE=BF=E0=AE=B2=E0=AF=
=8D<br>
&gt;<br>
=E0=AE=85=E0=AE=95=E0=AE=B4=E0=AE=BF&lt;<a href=3D"http://www.poetryinstone=
.in/lang/ta/2009/11/06/the-moat-around-the-tanjore-big-temple.html">http://=
www.poetryin<wbr>stone.in/<wbr>lang/ta/2009/<wbr>11/06/the-<wbr>moa\<br>
t-around-the-<wbr>tanjore-big-<wbr>temple.html</a>&gt;<br>
&gt;<br>
&gt; &lt;<a href=3D"http://www.poetryinstone.in/wp-admin/post.php?action=3D=
edit&amp;post=3D2720">http://www.poetryin<wbr>stone.in/<wbr>wp-admin/<wbr>p=
ost.php?<wbr>action=3Dedit&amp;<wbr>post=3D2720</a>&gt;<br>
&gt;<br>
&gt; =E0=AE=9A=E0=AE=AE=E0=AF=80=E0=AE=AA=E0=AE=A4=E0=AF=8D=E0=AE=A4=E0=AE=
=BF=E0=AE=AF<br>
=E0=AE=A8=E0=AE=BE=E0=AE=B3=E0=AF=87=E0=AE=9F=E0=AF=8D=E0=AE=9F=E0=AE=BF=E0=
=AE=B2=E0=AF=8D =E0=AE=A4=E0=AF=8A=E0=AE=B2=E0=AF=8D=E0=AE=B2=E0=AE=BF=E0=
=AE=AF=E0=AE=B2=E0=AF=8D<br>
=E0=AE=A4=E0=AF=81=E0=AE=B1=E0=AF=88 =E0=AE'=E0=AE=B0=E0=AF=81 =E0=AE=95=E0=
=AF=8B=E0=AE=9F=E0=AE=BF<br>
=E0=AE=B0=E0=AF=81=E0=AE=AA=E0=AE=BE=E0=AE=AF=E0=AF=8D =E0=AE=9A=E0=AF=86=
=E0=AE=B2=E0=AE=B5=E0=AE=BF=E0=AE=B2=E0=AF=8D<br>
=E0=AE=A4=E0=AE=9E=E0=AF=8D=E0=AE=9A=E0=AF=88 =E0=AE=AA=E0=AF=86=E0=AE=B0=
=E0=AE=BF=E0=AE=AF<br>
&gt; =E0=AE=95=E0=AF=8B=E0=AE=AF=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=85=E0=AE=
=95=E0=AE=B4=E0=AE=BF=E0=AE=AF=E0=AF=88<br>
=E0=AE=9A=E0=AF=86=E0=AE=AA=E0=AF=8D=E0=AE=AA=E0=AE=A9=E0=AE=BF=E0=AE=9F=E0=
=AE=AA=E0=AF=8D =E0=AE=AA=E0=AF=8B=E0=AE=95=E0=AE=BF=E0=AE=B1=E0=AE=A4=E0=
=AF=81<br>
=E0=AE=8E=E0=AE=A9=E0=AF=8D=E0=AE=B1 =E0=AE=9A=E0=AF=86=E0=AE=AF=E0=AF=8D=
=E0=AE=A4=E0=AE=BF<br>
=E0=AE=B5=E0=AE=BE=E0=AE=9A=E0=AE=BF=E0=AE=A4=E0=AF=8D=E0=AE=A4=E0=AF=81 =
=E0=AE=AE=E0=AE=95=E0=AE=BF=E0=AE=B4=E0=AF=8D=E0=AE=A8=E0=AF=8D=E0=AE=A4=E0=
=AF=87=E0=AE=A9=E0=AF=8D<br>
&gt;<br>
=E0=AE=9A=E0=AF=86=E0=AE=AF=E0=AF=8D=E0=AE=A4=E0=AE=BF&lt;<a href=3D"http:/=
/www.hindu.com/2009/11/05/stories/2009110558120100.htm">http://www.hindu.<w=
br>com/2009/<wbr>11/05/stories/<wbr>2009110\<br>
558120100.htm</a>&gt;.=E0=AE=89=E0=AE=9F=E0=AE=A9=E0=AF=87<br>
&gt; =E0=AE=A8=E0=AE=BF=E0=AE=A9=E0=AF=88=E0=AE=B5=E0=AF=81 =E0=AE=9A=E0=AE=
=BF=E0=AE=B2<br>
=E0=AE=86=E0=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=81=E0=AE=95=E0=AE=B3=E0=AF=81=E0=
=AE=95=E0=AF=8D=E0=AE=95=E0=AF=81<br>
=E0=AE=AE=E0=AF=81=E0=AE=A9=E0=AF=8D=E0=AE=A9=E0=AE=B0=E0=AF=8D =E0=AE=AA=
=E0=AE=BF=E0=AE=B0=E0=AE=BF=E0=AE=9F=E0=AF=8D=E0=AE=9F=E0=AE=BF=E0=AE=B7=E0=
=AF=8D<br>
=E0=AE=95=E0=AE=B0=E0=AF=81=E0=AE=B5=E0=AF=82=E0=AE=B2=E0=AE=A4=E0=AF=8D=E0=
=AE=A4=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=89=E0=AE=B3=E0=AF=8D=E0=AE=B3<br>
=E0=AE=9A=E0=AE=BF=E0=AE=B2 =E0=AE=AE=E0=AE=BF=E0=AE=95 =E0=AE=85=E0=AE=B0=
=E0=AE=BF=E0=AE=AF<br>
&gt; =E0=AE=AA=E0=AF=81=E0=AE=95=E0=AF=88=E0=AE=AA=E0=AF=8D=E0=AE=AA=E0=AE=
=9F=E0=AE=99=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=AF=88=E0=AE=AA=E0=AF=8D<br>
=E0=AE=AA=E0=AE=BE=E0=AE=B0=E0=AF=8D=E0=AE=B5=E0=AF=88=E0=AE=AF=E0=AE=BF=E0=
=AE=9F=E0=AF=8D=E0=AE=9F=E0=AE=A4=E0=AF=81=E0=AE=AE=E0=AF=8D.<br>
=E0=AE=85=E0=AE=A4=E0=AE=BF=E0=AE=B2=E0=AF=81=E0=AE=AE=E0=AF=8D<br>
=E0=AE=95=E0=AF=81=E0=AE=B1=E0=AE=BF=E0=AE=AA=E0=AF=8D=E0=AE=AA=E0=AE=BF=E0=
=AE=9F=E0=AF=81=E0=AE=AE=E0=AF=8D =E0=AE=AA=E0=AE=9F=E0=AE=BF=E0=AE=AF=E0=
=AE=BE=E0=AE=95<br>
=E0=AE'=E0=AE=B0=E0=AF=81 =E0=AE=AA=E0=AE=9F=E0=AE=AE=E0=AF=81=E0=AE=AE=E0=
=AF=8D!!!<br>
&gt;<br>
&gt;<br>
&gt;<br>
<a href=3D"http://www.poetryinstone.in/lang/ta/2009/11/06/the-moat-around-t=
he-tanjore-big-temple.html">http://www.poetryin<wbr>stone.in/<wbr>lang/ta/2=
009/<wbr>11/06/the-<wbr>moat-around-<wbr>the-tanjo\<br>
re-big-temple.<wbr>html</a><br>
&gt;<br>
&gt;<br>
&gt; Best regards,<br>
&gt; Vijay<br>
&gt; vj.episteme@<wbr>...<br>
&gt;<br>
</p>

    </div>
=20=20=20=20=20

    <!--~-|**|PrettyHtmlStart|**|-~-->
    <div style=3D"color: #fff; height: 0;">__._,_.___</div>

=20=20=20=20=20=20=20=20
=20=20
=20=20=20
    <div id=3D"ygrp-actbar" style=3D"clear: both; margin-bottom: 10px; whit=
e-space: nowrap; color: #666; padding-top: 15px;">
      <div>
        <a href=3D"mailto:sampath_srinivasaraghavan@yahoo.co.in?subject=3DR=
e: Fwd: [Poetry In Stone|=E0=AE=95=E0=AE=B2=E0=AF=8D=E0=AE=B2=E0=AE=BF=E0=
=AE=B2=E0=AF=87 =E0=AE=95=E0=AE=B2=E0=AF=88=E0=AE=B5=E0=AE=A3=E0=AF=8D=E0=
=AE=A3=E0=AE=AE=E0=AF=8D =E0=AE=95=E0=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=8B=E0=
=AE=AE=E0=AF=8D] The moat around the Tanjore Big temple | =E0=AE=A4=E0=AE=
=9E=E0=AF=8D=E0=AE=9A=E0=AF=88 =E0=AE=AA=E0=AF=86=E0=AE=B0=E0=AE=BF=E0=AE=
=AF =E0=AE=95=E0=AF=8B=E0=AE=AF=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=85=E0=AE=
=95=E0=AE=B4=E0=AE=BF">
          Reply to <span style=3D"font-weight: 700;">sender</span></a>
          | <a href=3D"mailto:ponniyinselvan@yahoogroups.com?subject=3DRe: =
Fwd: [Poetry In Stone|=E0=AE=95=E0=AE=B2=E0=AF=8D=E0=AE=B2=E0=AE=BF=E0=AE=
=B2=E0=AF=87 =E0=AE=95=E0=AE=B2=E0=AF=88=E0=AE=B5=E0=AE=A3=E0=AF=8D=E0=AE=
=A3=E0=AE=AE=E0=AF=8D =E0=AE=95=E0=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=8B=E0=AE=
=AE=E0=AF=8D] The moat around the Tanjore Big temple | =E0=AE=A4=E0=AE=9E=
=E0=AF=8D=E0=AE=9A=E0=AF=88 =E0=AE=AA=E0=AF=86=E0=AE=B0=E0=AE=BF=E0=AE=AF =
=E0=AE=95=E0=AF=8B=E0=AE=AF=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=85=E0=AE=95=
=E0=AE=B4=E0=AE=BF">
        Reply to <span style=3D"font-weight: 700;">group</span></a>
      </div>

                <a href=3D"http://groups.yahoo.com/group/ponniyinselvan/mes=
sage/35339;_ylc=3DX3oDMTM2aDhkZnVlBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ3Jwc=
3BJZAMxNzA1MDE5NTA5BG1zZ0lkAzM1MzQwBHNlYwNmdHIEc2xrA3Z0cGMEc3RpbWUDMTI1NzUw=
NzI5MQR0cGNJZAMzNTMzOQ--">Messages in this topic</a>
          (<span style=3D"font-weight: 700;">2</span>)
          </div>=20
<!------- Start Nav Bar ------>
<!-- |**|begin egp html banner|**| -->
<!-- |**|end egp html banner|**| -->

<!-- |**|begin egp html banner|**| -->
<div id=3D"ygrp-vital" style=3D"background-color: #e0ecee; font-family: Ver=
dana; font-size: 10px; margin-bottom: 10px; padding: 10px;">
      <span id=3D"vithd" style=3D"font-weight: bold; color: #333; text-tran=
sform: uppercase; ">Recent Activity:</span>

    <ul style=3D"list-style-type: none; margin: 0; padding: 0; display: inl=
ine;">
            <li style=3D"border-right: 1px solid #000; font-weight: 700; di=
splay: inline; padding: 0 5px; margin-left: 0;">
      <span class=3D"cat"><a href=3D"http://groups.yahoo.com/group/ponniyin=
selvan/members;_ylc=3DX3oDMTJmdmM2ajl0BF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ=
3Jwc3BJZAMxNzA1MDE5NTA5BHNlYwN2dGwEc2xrA3ZtYnJzBHN0aW1lAzEyNTc1MDcyOTE-?o=
=3D6" style=3D"text-decoration: none;">New Members</a></span>
      <span class=3D"ct" style=3D"color: #ff7900;">13</span>
    </li>
                                              </ul>
=20=20=20=20
  <div style=3D"clear: both; padding-top: 2px; color: #1e66ae;">
    <a href=3D"http://groups.yahoo.com/group/ponniyinselvan;_ylc=3DX3oDMTJl=
ZGYybGRhBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ3Jwc3BJZAMxNzA1MDE5NTA5BHNlYwN=
2dGwEc2xrA3ZnaHAEc3RpbWUDMTI1NzUwNzI5MQ--" style=3D"border-right: 1px solid=
 #000; padding-right: 5px; margin-right: 2px; text-decoration: none;">Visit=
 Your Group</a>
    <a href=3D"http://groups.yahoo.com/group/ponniyinselvan/post;_ylc=3DX3o=
DMTJlamRvM2kyBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ3Jwc3BJZAMxNzA1MDE5NTA5BH=
NlYwNmdHIEc2xrA250cGMEc3RpbWUDMTI1NzUwNzI5MQ--" style=3D"font-weight: 700; =
text-decoration: none;">Start a New Topic</a>
  </div>
</div>

        <div id=3D"ygrp-grft" style=3D"font-family: Verdana; font-size: 12p=
x; padding: 15px 0;">
=20=20=20=20=20=20
<!-- |**|begin egp html banner|**| -->

      ---------------------------------------------------------------------=
------<BR>
DISCLAIMER: The Founder / Convenor of the Group and / or its Moderators do =
<BR>
not subscribe to the views of the Members and subscriber alone is <BR>
responsible to defend the view of the subscriber if and when challenged by =
any person/s or Authority and/or by the process of Law.<BR>
<BR>
Members are requested to ensure that copyright issues are not violated<BR>
---------------------------------------------------------------------------=
-<BR>
Visit <a href=3D"http://ponniyinselvan.in">http://ponniyinselvan.in</a> to =
find archived messages<BR>
Visit <a href=3D"http://festival2009.ponniyinselvan.in">http://festival2009=
.ponniyinselvan.in</a> to find out about PSVP Vizha<BR>
---------------------------------------------------------------------------=
<BR>
=20=20=20=20=20=20
<!-- |**|end egp html banner|**| -->

    </div>
            <div id=3D"ygrp-mkp" style=3D"border: 1px solid #d8d8d8; clear:=
 both; float: left; font-family: Arial; margin: 5px 0 10px 0; padding: 0 10=
px;">
      <div id=3D"hd" style=3D"color: #628c2a; font-size: 85%; font-weight: =
700; line-height: 122%; margin: 10px 0;">MARKETPLACE</div>
      <div id=3D"ads" style=3D"margin-bottom: 10px;">
                  <div class=3D"ad" style=3D"color: #628C2A; font-family: A=
rial; font-weight: 700; padding: 0 0;">
            <a href=3D"http://us.ard.yahoo.com/SIG=3D14k7sgubi/M=3D493064.1=
2016295.13271503.10835568/D=3Dgroups/S=3D1705019509:MKP1/Y=3DYAHOO/EXP=3D12=
57514491/L=3D/B=3DDtZ4J0PDhEc-/J=3D1257507291735690/K=3DnxG_Kap0n4ivdmFRcB0=
ZcQ/A=3D5697381/R=3D0/SIG=3D11eaa5dke/*http://groups.yahoo.com/group/mompow=
ergroup/">Mom Power: Discover the community of moms doing more for their fa=
milies, for the world and for each other</a>          </div>
                              </div>
    </div>
=20=20
<div id=3D"ft" style=3D"font-family: Arial; font-size: 11px; margin-top: 5p=
x; padding: 0 2px 0 0; clear: both;">
  <a href=3D"http://groups.yahoo.com/;_ylc=3DX3oDMTJkbHFpN2p2BF9TAzk3MzU5Nz=
E0BGdycElkAzYyNDg5MzEEZ3Jwc3BJZAMxNzA1MDE5NTA5BHNlYwNmdHIEc2xrA2dmcARzdGltZ=
QMxMjU3NTA3Mjkx" style=3D"float: left;"><img src=3D"http://l.yimg.com/a/i/u=
s/yg/logo/us.gif" height=3D"15" width=3D"137" alt=3D"Yahoo! Groups" style=
=3D"border: 0;"/></a>
  <div style=3D"color: #747575; float: right;">Switch to: <a href=3D"mailto=
:ponniyinselvan-traditional@yahoogroups.com?subject=3DChange Delivery Forma=
t: Traditional" style=3D"text-decoration: none;">Text-Only</a>, <a href=3D"=
mailto:ponniyinselvan-digest@yahoogroups.com?subject=3DEmail Delivery: Dige=
st" class=3D"margin-rt" style=3D"text-decoration: none;">Daily Digest</a> &=
bull; <a href=3D"mailto:ponniyinselvan-unsubscribe@yahoogroups.com?subject=
=3DUnsubscribe" style=3D"text-decoration: none;">Unsubscribe</a> &bull; <a =
href=3D"http://docs.yahoo.com/info/terms/" style=3D"text-decoration: none;"=
>Terms of Use</a></div>
</div>

<!-- |**|end egp html banner|**| -->

  </div> <!-- ygrp-msg -->

  <!-- Sponsor -->
  <!-- |**|begin egp html banner|**| -->
  <div id=3D"ygrp-sponsor" style=3D"width:160px; float:right; clear:none; m=
argin:0 0 25px 0; background: #fff;">

<!-- Start Recommendations -->
<div id=3D"ygrp-reco">
     </div>
<!-- End Recommendations -->



  </div>   <!-- |**|end egp html banner|**| -->

  <div style=3D"clear:both; color: #FFF; font-size:1px;">.</div>
</div>

  <img src=3D"http://geo.yahoo.com/serv?s=3D97359714/grpId=3D6248931/grpspI=
d=3D1705019509/msgId=3D35340/stime=3D1257507291/nc1=3D4025373/nc2=3D5597441=
/nc3=3D5689702" width=3D"1" height=3D"1"> <br>

<div style=3D"color: #fff; height: 0;">__,_._,___</div>
<!--~-|**|PrettyHtmlEnd|**|-~-->

</body>

<!--~-|**|PrettyHtmlStart|**|-~-->
<head>
  <style type=3D"text/css">
  <!--
  #ygrp-mkp {
  border: 1px solid #d8d8d8;
  font-family: Arial;
  margin: 10px 0;
  padding: 0 10px;
}

#ygrp-mkp hr {
  border: 1px solid #d8d8d8;
}

#ygrp-mkp #hd {
  color: #628c2a;
  font-size: 85%;
  font-weight: 700;
  line-height: 122%;
  margin: 10px 0;
}

#ygrp-mkp #ads {
  margin-bottom: 10px;
}

#ygrp-mkp .ad {
  padding: 0 0;
}

#ygrp-mkp .ad a {
  color: #0000ff;
  text-decoration: none;
}
  #ygrp-sponsor #ygrp-lc {
  font-family: Arial;
}

#ygrp-sponsor #ygrp-lc #hd {
  margin: 10px 0px;
  font-weight: 700;
  font-size: 78%;
  line-height: 122%;
}

#ygrp-sponsor #ygrp-lc .ad {
  margin-bottom: 10px;
  padding: 0 0;
}

  a {
    color: #1e66ae;
  }

  #actions {
    font-family: Verdana;
    font-size: 11px;
    padding: 10px 0;
  }

  #activity {
    background-color: #e0ecee;
    float: left;
    font-family: Verdana;
    font-size: 10px;
    padding: 10px;
  }

  #activity span {
    font-weight: 700;
  }

  #activity span:first-child {
    text-transform: uppercase;
  }

  #activity span a {
    color: #5085b6;
    text-decoration: none;
  }

  #activity span span {
    color: #ff7900;
  }

  #activity span .underline {
    text-decoration: underline;
  }

  .attach {
    clear: both;
    display: table;
    font-family: Arial;
    font-size: 12px;
    padding: 10px 0;
    width: 400px;
  }

  .attach div a {
    text-decoration: none;
  }

  .attach img {
    border: none;
    padding-right: 5px;
  }

  .attach label {
    display: block;
    margin-bottom: 5px;
  }

  .attach label a {
    text-decoration: none;
  }
=20=20
  blockquote {
    margin: 0 0 0 4px;
  }

  .bold {
    font-family: Arial;
    font-size: 13px;
    font-weight: 700;
  }

  .bold a {
    text-decoration: none;
  }

  dd.last p a {
    font-family: Verdana;
    font-weight: 700;
  }

  dd.last p span {
    margin-right: 10px;
    font-family: Verdana;
    font-weight: 700;
  }

  dd.last p span.yshortcuts {
    margin-right: 0;
  }

  div.attach-table div div a {
    text-decoration: none;
  }

  div.attach-table {
    width: 400px;
  }

  div.file-title a, div.file-title a:active, div.file-title a:hover, div.fi=
le-title a:visited {
    text-decoration: none;
  }

  div.photo-title a, div.photo-title a:active, div.photo-title a:hover, div=
.photo-title a:visited {
    text-decoration: none;
  }

  div#ygrp-mlmsg #ygrp-msg p a span.yshortcuts {
    font-family: Verdana;
    font-size: 10px;
    font-weight: normal;
  }

  .green {
    color: #628c2a;
  }

  .MsoNormal {
    margin: 0 0 0 0;
  }

  o {
    font-size: 0;
  }

  #photos div {
    float: left;
    width: 72px;
  }

  #photos div div {
    border: 1px solid #666666;
    height: 62px;
    overflow: hidden;
    width: 62px;
  }

  #photos div label {
    color: #666666;
    font-size: 10px;
    overflow: hidden;
    text-align: center;
    white-space: nowrap;
    width: 64px;
  }

  #reco-category {
    font-size: 77%;
  }

  #reco-desc {
    font-size: 77%;
  }

  .replbq {
    margin: 4px;
  }

  #ygrp-actbar div a:first-child {
   /* border-right: 0px solid #000;*/
    margin-right: 2px;
    padding-right: 5px;
  }

  #ygrp-mlmsg {
    font-size: 13px;
    font-family: Arial, helvetica,clean, sans-serif;
    *font-size: small;
    *font: x-small;
  }

  #ygrp-mlmsg table {
    font-size: inherit;
    font: 100%;
  }

  #ygrp-mlmsg select, input, textarea {
    font: 99% Arial, Helvetica, clean, sans-serif;
  }

  #ygrp-mlmsg pre, code {
    font:115% monospace;
    *font-size:100%;
  }

  #ygrp-mlmsg * {
    line-height: 1.22em;
  }

  #ygrp-mlmsg #logo {
    padding-bottom: 10px;
  }

  #ygrp-mlmsg a {
    color: #1E66AE;
  }

  #ygrp-msg p a {
    font-family: Verdana;
  }

  #ygrp-msg p#attach-count span {
    color: #1E66AE;
    font-weight: 700;
  }

  #ygrp-reco #reco-head {
    color: #ff7900;
    font-weight: 700;
  }

  #ygrp-reco {
    margin-bottom: 20px;
    padding: 0px;
  }

  #ygrp-sponsor #ov li a {
    font-size: 130%;
    text-decoration: none;
  }

  #ygrp-sponsor #ov li {
    font-size: 77%;
    list-style-type: square;
    padding: 6px 0;
  }=20

  #ygrp-sponsor #ov ul {
    margin: 0;
    padding: 0 0 0 8px;
  }

  #ygrp-text {
    font-family: Georgia;
  }

  #ygrp-text p {
    margin: 0 0 1em 0;
  }

  #ygrp-text tt {
    font-size: 120%;
  }

  #ygrp-vital ul li:last-child {
    border-right: none !important;=20
  }=20
  -->
  </style>
</head>

<!--~-|**|PrettyHtmlEnd|**|-~-->
</html>
<!-- end group email -->


--kxFkv1tbrjBYnsxZexqtqb0QKPyrVloqsV0vnu4--