Delivered-To: ygroup@ponniyinselvan.in
Received: by 10.231.129.133 with SMTP id o5cs235099ibs;
        Sun, 8 Nov 2009 05:32:33 -0800 (PST)
Received: by 10.114.86.2 with SMTP id j2mr11293825wab.159.1257687152989;
        Sun, 08 Nov 2009 05:32:32 -0800 (PST)
Return-Path: <sentto-6248931-35363-1257687151-ygroup=ponniyinselvan.in@returns.groups.yahoo.com>
Received: from n64d.bullet.mail.sp1.yahoo.com (n64d.bullet.mail.sp1.yahoo.com [98.136.45.89])
        by mx.google.com with SMTP id 26si4354396pxi.90.2009.11.08.05.32.31;
        Sun, 08 Nov 2009 05:32:31 -0800 (PST)
Received-SPF: pass (google.com: domain of sentto-6248931-35363-1257687151-ygroup=ponniyinselvan.in@returns.groups.yahoo.com designates 98.136.45.89 as permitted sender) client-ip=98.136.45.89;
Authentication-Results: mx.google.com; spf=pass (google.com: domain of sentto-6248931-35363-1257687151-ygroup=ponniyinselvan.in@returns.groups.yahoo.com designates 98.136.45.89 as permitted sender) smtp.mail=sentto-6248931-35363-1257687151-ygroup=ponniyinselvan.in@returns.groups.yahoo.com; dkim=pass header.i=@yahoogroups.com
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=yahoogroups.com; s=lima; t=1257687151; bh=qRqO2++UIBJKMLE2P+hyC8s5wsjlxWaTfocURH0OC/M=; h=Received:Received:X-Yahoo-Newman-Id:X-Sender:X-Apparently-To:X-Received:X-Received:X-Received:X-Received:Message-ID:X-YMail-OSG:X-Received:X-Mailer:To:X-Originating-IP:X-eGroups-Msg-Info:From:X-Yahoo-Profile:Sender:MIME-Version:Mailing-List:Delivered-To:List-Id:Precedence:List-Unsubscribe:Date:Subject:Reply-To:X-Yahoo-Newman-Property:Content-Type; b=VGsVaqiLEYyCTBODJENKeVd3eIz5z/RjSQBuyhuAHgh53U6nQHUcu18g0gWZibTBLPBOCdMlmtGPj1FzA8psDV2ENFWeLGniMSvMrj2GFztew72i5bovrbVK3w7DfG/W
DomainKey-Signature: a=rsa-sha1; q=dns; c=nofws; s=lima; d=yahoogroups.com;
	b=m5nIxIwdOII3s+7l4FMJQigcQtbpZxGOIjd2Td+5brJWwVlexlVMWgyZ7SS7cDZXUCR4PCTOZ+ECtIE/JfyT/dbxoeeeTbMiwiGmsiRRy8hLIzzhn6vlDYr/yAvqJOYa;
Received: from [69.147.65.150] by n64.bullet.mail.sp1.yahoo.com with NNFMP; 08 Nov 2009 13:32:31 -0000
Received: from [98.137.34.41] by t7.bullet.mail.sp1.yahoo.com with NNFMP; 08 Nov 2009 13:32:31 -0000
X-Yahoo-Newman-Id: 6248931-m35363
X-Sender: amudamtamil@yahoo.co.in
X-Apparently-To: ponniyinselvan@yahoogroups.com
X-Received: (qmail 52042 invoked from network); 8 Nov 2009 13:32:30 -0000
X-Received: from unknown (66.196.94.106)
  by m5.grp.sp2.yahoo.com with QMQP; 8 Nov 2009 13:32:30 -0000
X-Received: from unknown (HELO web7603.mail.in.yahoo.com) (202.86.4.22)
  by mta2.grp.re1.yahoo.com with SMTP; 8 Nov 2009 13:32:29 -0000
X-Received: (qmail 31216 invoked by uid 60001); 8 Nov 2009 13:31:11 -0000
Message-ID: <705200.31204.qm@web7603.mail.in.yahoo.com>
X-YMail-OSG: PPlvSXcVM1leNdwGRNwaXQlXzR1cFAY1h3uuq5o8SsfwAHhI51Aq344tZrG8ukIDAQvCrMsA4NXlZgEl4RG8WUktdrNBqo2RlbqjfWKHTo61zQkqf8EO9yWy8w8XiBofvRSTgVi6ZDXkhbH5lucOlVQ7K1gkfqt9aDGoQaHYwqWuZVdiouFJfjEeBxg0WL8j7ySrU.hZwnMfbUQEhkGCq7p6bn4oJGXIdmksp1dw9ioaAAos91JnT_rQguxnz8koxKdP5h_j
X-Received: from [59.92.125.126] by web7603.mail.in.yahoo.com via HTTP; Sun, 08 Nov 2009 19:01:11 IST
X-Mailer: YahooMailClassic/8.1.6 YahooMailWebService/0.8.100.260964
To: korea_tamilnanbargal@yahoogroups.com, LankanTamil@yahoogroups.com,
  Malaysian-Tamils@yahoogroups.com, manalan_nanjil@yahoogroups.com,
  marthandam_friends@yahoogroups.com, montrealtamil@yahoogroups.com,
  mytamilsongs@yahoogroups.com, MuthuFriends@yahoogroups.com,
  naanjil@yahoogroups.com, nagercoil@yahoogroups.com,
  Nagercoil_frns@yahoogroups.com, NagercoilCyberFriends@yahoogroups.com,
  nagerkoil@yahoogroups.com, NanjilCyberFriends@yahoogroups.com,
  NanjilGuys@yahoogroups.com, NGKians@yahoogroups.com,
  NJTamilEvents@yahoogroups.com, ntyo_talk@yahoogroups.com,
  pmadurai@yahoogroups.com, ponniyinselvan@yahoogroups.com,
  priyas_tamil_world@yahoogroups.com, riyadhtamilsangam@yahoogroups.com,
  Sac_Sangamam@yahoogroups.com
X-Originating-IP: 202.86.4.22
X-eGroups-Msg-Info: 1:12:0:0:0
From: Aldrin Britto <amudamtamil@yahoo.co.in>
X-Yahoo-Profile: amudamtamil
Sender: ponniyinselvan@yahoogroups.com
MIME-Version: 1.0
Mailing-List: list ponniyinselvan@yahoogroups.com; contact ponniyinselvan-owner@yahoogroups.com
Delivered-To: mailing list ponniyinselvan@yahoogroups.com
List-Id: <ponniyinselvan.yahoogroups.com>
Precedence: bulk
List-Unsubscribe: <mailto:ponniyinselvan-unsubscribe@yahoogroups.com>
Date: Sun, 8 Nov 2009 19:01:11 +0530 (IST)
Subject: [ponniyinselvan] =?utf-8?B?4K614K6+4K604K+N4K614K6/4K6y4K+NIOCuieCur+CusOCusuCuvuCurg==?=
 =?utf-8?B?4K+NLi4u?=
Reply-To: ponniyinselvan@yahoogroups.com
X-Yahoo-Newman-Property: groups-email-ff-m
Content-Type: multipart/alternative;
 boundary="0-2119700399-1257687071=:31204"

--0-2119700399-1257687071=:31204
Content-Type: text/plain; charset=utf-8
Content-Transfer-Encoding: quoted-printable

=E0=AE=89=E0=AE=B2=E0=AE=95=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=9A=E0=AE=BE=
=E0=AE=A4=E0=AE=BF=E0=AE=A4=E0=AF=8D=E0=AE=A4 =E0=AE=9A=E0=AE=BE=E0=AE=A4=
=E0=AE=A9=E0=AF=88=E0=AE=AF=E0=AE=BE=E0=AE=B3=E0=AE=B0=E0=AF=8D=E0=AE=95=E0=
=AE=B3=E0=AF=8D =E0=AE=8E=E0=AE=A4=E0=AF=88 =E0=AE=AA=E0=AE=BF=E0=AE=A9=E0=
=AF=8D=E0=AE=AA=E0=AE=B1=E0=AF=8D=E0=AE=B1=E0=AE=BF=E0=AE=A9=E0=AE=BE=E0=AE=
=B0=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=AF=8D, =E0=AE=85=E0=AE=B5=E0=AE=B0=E0=AF=
=8D=E0=AE=95=E0=AE=B3=E0=AE=A4=E0=AF=81 =E0=AE=87=E0=AE=AE=E0=AE=BE=E0=AE=
=B2=E0=AE=AF =E0=AE=9A=E0=AE=BE=E0=AE=A4=E0=AE=A9=E0=AF=88=E0=AE=95=E0=AE=
=B3=E0=AF=81=E0=AE=95=E0=AF=8D=E0=AE=95=E0=AF=81 =E0=AE=8E=E0=AE=A9=E0=AF=
=8D=E0=AE=A9 =E0=AE=95=E0=AE=BE=E0=AE=B0=E0=AE=A3=E0=AE=AE=E0=AF=8D =E0=AE=
=A4=E0=AF=86=E0=AE=B0=E0=AE=BF=E0=AE=A8=E0=AF=8D=E0=AE=A4=E0=AF=81=E0=AE=95=
=E0=AF=8D =E0=AE=95=E0=AF=8A=E0=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=81 =E0=AE=A8=
=E0=AF=80=E0=AE=99=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=AF=81=E0=AE=AE=E0=AF=8D =
=E0=AE=9A=E0=AE=BE=E0=AE=A4=E0=AE=BF=E0=AE=95=E0=AF=8D=E0=AE=95 =E0=AE=A4=
=E0=AE=AF=E0=AE=BE=E0=AE=B0=E0=AE=BE=E0=AE=95=E0=AF=81=E0=AE=99=E0=AF=8D=E0=
=AE=95=E0=AE=B3=E0=AF=8D.
=C2=A0
=E0=AE=89=E0=AE=B2=E0=AE=95 =E0=AE=A4=E0=AE=B0=E0=AE=AE=E0=AF=8D =E0=AE=B5=
=E0=AE=BE=E0=AE=AF=E0=AF=8D=E0=AE=A8=E0=AF=8D=E0=AE=A4 =E0=AE=9A=E0=AF=81=
=E0=AE=AF=E0=AE=AE=E0=AF=81=E0=AE=A9=E0=AF=8D=E0=AE=A9=E0=AF=87=E0=AE=B1=E0=
=AF=8D=E0=AE=B1 =E0=AE=AA=E0=AE=AF=E0=AE=BF=E0=AE=B1=E0=AF=8D=E0=AE=9A=E0=
=AE=BF=E0=AE=AF=E0=AE=BE=E0=AE=B3=E0=AE=B0=E0=AF=8D =E0=AE=B5=E0=AE=B4=E0=
=AE=99=E0=AF=8D=E0=AE=95=E0=AF=81=E0=AE=AE=E0=AF=8D =E0=AE=AA=E0=AE=AF=E0=
=AE=BF=E0=AE=B1=E0=AF=8D=E0=AE=9A=E0=AE=BF =E0=AE=A8=E0=AF=80=E0=AE=99=E0=
=AF=8D=E0=AE=95=E0=AE=B4=E0=AF=81=E0=AE=AE=E0=AF=8D =E0=AE=95=E0=AE=B2=E0=
=AE=A8=E0=AF=8D=E0=AE=A4=E0=AF=81=E0=AE=95=E0=AF=8D =E0=AE=95=E0=AF=8A=E0=
=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=81 =E0=AE=AA=E0=AE=AF=E0=AE=A9=E0=AF=8D =E0=
=AE=AA=E0=AF=86=E0=AE=B1=E0=AF=81=E0=AE=99=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=AF=
=8D.
=C2=A0
=E0=AE=AA=E0=AE=AF=E0=AE=BF=E0=AE=B1=E0=AF=8D=E0=AE=9A=E0=AE=BF =E0=AE=87=
=E0=AE=AA=E0=AF=8D=E0=AE=AA=E0=AF=8B=E0=AE=A4=E0=AF=81 =E0=AE=A4=E0=AE=AE=
=E0=AE=BF=E0=AE=B4=E0=AE=95=E0=AE=A4=E0=AF=8D=E0=AE=A4=E0=AE=BF=E0=AE=A9=E0=
=AF=8D =E0=AE=A4=E0=AF=86=E0=AE=A9=E0=AF=8D =E0=AE=A8=E0=AE=95=E0=AE=B0=E0=
=AE=BE=E0=AE=A9 =E0=AE=AA=E0=AE=BE=E0=AE=B3=E0=AF=88=E0=AE=AF=E0=AE=99=E0=
=AF=8D=E0=AE=95=E0=AF=8B=E0=AE=9F=E0=AF=8D=E0=AE=9F=E0=AF=88=E0=AE=AF=E0=AE=
=BF=E0=AE=B2=E0=AF=8D =E0=AE=A8=E0=AE=B5=E0=AE=AE=E0=AF=8D=E0=AE=AA=E0=AE=
=B0=E0=AF=8D=C2=A015 - =E0=AE=86=E0=AE=AE=E0=AF=8D =E0=AE=A4=E0=AF=87=E0=AE=
=A4=E0=AE=BF (=E0=AE=9E=E0=AE=BE=E0=AE=AF=E0=AE=BF=E0=AE=B1=E0=AF=8D=E0=AE=
=B1=E0=AF=81=E0=AE=95=E0=AF=8D=E0=AE=95=E0=AE=BF=E0=AE=B4=E0=AE=AE=E0=AF=88=
) =E0=AE=A8=E0=AE=9F=E0=AF=88=E0=AE=AA=E0=AF=86=E0=AE=B1=E0=AF=81=E0=AE=95=
=E0=AE=BF=E0=AE=B1=E0=AE=A4=E0=AF=81.
=C2=A0
=E0=AE=AE=E0=AE=BF=E0=AE=95=E0=AE=95=E0=AF=8D =E0=AE=95=E0=AF=81=E0=AE=B1=
=E0=AF=88=E0=AE=A8=E0=AF=8D=E0=AE=A4 =E0=AE=8E=E0=AE=A3=E0=AF=8D=E0=AE=A3=
=E0=AE=BF=E0=AE=95=E0=AF=8D=E0=AE=95=E0=AF=88=E0=AE=AF=E0=AE=BF=E0=AE=B2=E0=
=AE=BE=E0=AE=A9 =E0=AE=A8=E0=AE=AA=E0=AE=B0=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=
=AF=87=C2=A0=E0=AE=85=E0=AE=A9=E0=AF=81=E0=AE=AE=E0=AE=A4=E0=AE=BF=E0=AE=95=
=E0=AF=8D=E0=AE=95=E0=AE=AA=E0=AF=8D=E0=AE=AA=E0=AE=9F=E0=AF=81=E0=AE=95=E0=
=AE=BF=E0=AE=A9=E0=AF=8D=E0=AE=B1=E0=AE=A9=E0=AE=B0=E0=AF=8D. =E0=AE=95=E0=
=AE=B2=E0=AE=A8=E0=AF=8D=E0=AE=A4=E0=AF=81=E0=AE=95=E0=AF=8D =E0=AE=95=E0=
=AF=8A=E0=AE=B3=E0=AF=8D=E0=AE=B3 =E0=AE=B5=E0=AE=BF=E0=AE=B0=E0=AF=81=E0=
=AE=AE=E0=AF=8D=E0=AE=AA=E0=AF=81=E0=AE=B5=E0=AF=8B=E0=AE=B0=E0=AF=8D =E0=
=AE=AE=E0=AF=81=E0=AE=A9=E0=AF=8D=E0=AE=AA=E0=AE=A4=E0=AE=BF=E0=AE=B5=E0=AF=
=81 =E0=AE=9A=E0=AF=86=E0=AE=AF=E0=AF=8D=E0=AE=A4=E0=AF=81 =E0=AE=95=E0=AF=
=8A=E0=AE=B3=E0=AF=8D=E0=AE=B3=E0=AE=B5=E0=AF=81=E0=AE=AE=E0=AF=8D.
=C2=A0
=E0=AE=A4=E0=AF=8A=E0=AE=9F=E0=AE=B0=E0=AF=8D=E0=AE=AA=E0=AF=81=E0=AE=95=E0=
=AF=8D=E0=AE=95=E0=AF=81:
9487177604
9345545658


      The INTERNET now has a personality. YOURS! See your Yahoo! Homepage. =
http://in.yahoo.com/
--0-2119700399-1257687071=:31204
Content-Type: text/html; charset=UTF-8
Content-Transfer-Encoding: quoted-printable




<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/htm=
l4/strict.dtd">
<html>
<head>
</head>







<body style=3D"background-color: #fff;">
<span style=3D"display:none">&nbsp;</span>

<!--~-|**|PrettyHtmlStartT|**|-~-->
<div id=3D"ygrp-mlmsg" style=3D"position:relative;">
  <div id=3D"ygrp-msg" style=3D"z-index: 1;">
<!--~-|**|PrettyHtmlEndT|**|-~-->

    <div id=3D"ygrp-text" >
=20=20=20=20=20=20
=20=20=20=20=20=20
      <p><table cellspacing=3D"0" cellpadding=3D"0" border=3D"0"><tr><td va=
lign=3D"top" style=3D"font: inherit;"><DIV>=E0=AE=89=E0=AE=B2=E0=AE=95=E0=
=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=9A=E0=AE=BE=E0=AE=A4=E0=AE=BF=E0=AE=A4=E0=
=AF=8D=E0=AE=A4 =E0=AE=9A=E0=AE=BE=E0=AE=A4=E0=AE=A9=E0=AF=88=E0=AE=AF=E0=
=AE=BE=E0=AE=B3=E0=AE=B0=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=AF=8D =E0=AE=8E=E0=
=AE=A4=E0=AF=88 =E0=AE=AA=E0=AE=BF=E0=AE=A9=E0=AF=8D=E0=AE=AA=E0=AE=B1=E0=
=AF=8D=E0=AE=B1=E0=AE=BF=E0=AE=A9=E0=AE=BE=E0=AE=B0=E0=AF=8D=E0=AE=95=E0=AE=
=B3=E0=AF=8D, =E0=AE=85=E0=AE=B5=E0=AE=B0=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=AE=
=A4=E0=AF=81 =E0=AE=87=E0=AE=AE=E0=AE=BE=E0=AE=B2=E0=AE=AF =E0=AE=9A=E0=AE=
=BE=E0=AE=A4=E0=AE=A9=E0=AF=88=E0=AE=95=E0=AE=B3=E0=AF=81=E0=AE=95=E0=AF=8D=
=E0=AE=95=E0=AF=81 =E0=AE=8E=E0=AE=A9=E0=AF=8D=E0=AE=A9 =E0=AE=95=E0=AE=BE=
=E0=AE=B0=E0=AE=A3=E0=AE=AE=E0=AF=8D =E0=AE=A4=E0=AF=86=E0=AE=B0=E0=AE=BF=
=E0=AE=A8=E0=AF=8D=E0=AE=A4=E0=AF=81=E0=AE=95=E0=AF=8D =E0=AE=95=E0=AF=8A=
=E0=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=81 =E0=AE=A8=E0=AF=80=E0=AE=99=E0=AF=8D=
=E0=AE=95=E0=AE=B3=E0=AF=81=E0=AE=AE=E0=AF=8D =E0=AE=9A=E0=AE=BE=E0=AE=A4=
=E0=AE=BF=E0=AE=95=E0=AF=8D=E0=AE=95 =E0=AE=A4=E0=AE=AF=E0=AE=BE=E0=AE=B0=
=E0=AE=BE=E0=AE=95=E0=AF=81=E0=AE=99=E0=AF=8D=E0=AE=95=E0=AE=B3=E0=AF=8D.</=
DIV>
<DIV>&nbsp;</DIV>
<DIV>=E0=AE=89=E0=AE=B2=E0=AE=95 =E0=AE=A4=E0=AE=B0=E0=AE=AE=E0=AF=8D =E0=
=AE=B5=E0=AE=BE=E0=AE=AF=E0=AF=8D=E0=AE=A8=E0=AF=8D=E0=AE=A4 =E0=AE=9A=E0=
=AF=81=E0=AE=AF=E0=AE=AE=E0=AF=81=E0=AE=A9=E0=AF=8D=E0=AE=A9=E0=AF=87=E0=AE=
=B1=E0=AF=8D=E0=AE=B1 =E0=AE=AA=E0=AE=AF=E0=AE=BF=E0=AE=B1=E0=AF=8D=E0=AE=
=9A=E0=AE=BF=E0=AE=AF=E0=AE=BE=E0=AE=B3=E0=AE=B0=E0=AF=8D =E0=AE=B5=E0=AE=
=B4=E0=AE=99=E0=AF=8D=E0=AE=95=E0=AF=81=E0=AE=AE=E0=AF=8D =E0=AE=AA=E0=AE=
=AF=E0=AE=BF=E0=AE=B1=E0=AF=8D=E0=AE=9A=E0=AE=BF =E0=AE=A8=E0=AF=80=E0=AE=
=99=E0=AF=8D=E0=AE=95=E0=AE=B4=E0=AF=81=E0=AE=AE=E0=AF=8D =E0=AE=95=E0=AE=
=B2=E0=AE=A8=E0=AF=8D=E0=AE=A4=E0=AF=81=E0=AE=95=E0=AF=8D =E0=AE=95=E0=AF=
=8A=E0=AE=A3=E0=AF=8D=E0=AE=9F=E0=AF=81 =E0=AE=AA=E0=AE=AF=E0=AE=A9=E0=AF=
=8D =E0=AE=AA=E0=AF=86=E0=AE=B1=E0=AF=81=E0=AE=99=E0=AF=8D=E0=AE=95=E0=AE=
=B3=E0=AF=8D.</DIV>
<DIV>&nbsp;</DIV>
<DIV>=E0=AE=AA=E0=AE=AF=E0=AE=BF=E0=AE=B1=E0=AF=8D=E0=AE=9A=E0=AE=BF =E0=AE=
=87=E0=AE=AA=E0=AF=8D=E0=AE=AA=E0=AF=8B=E0=AE=A4=E0=AF=81 =E0=AE=A4=E0=AE=
=AE=E0=AE=BF=E0=AE=B4=E0=AE=95=E0=AE=A4=E0=AF=8D=E0=AE=A4=E0=AE=BF=E0=AE=A9=
=E0=AF=8D =E0=AE=A4=E0=AF=86=E0=AE=A9=E0=AF=8D =E0=AE=A8=E0=AE=95=E0=AE=B0=
=E0=AE=BE=E0=AE=A9 =E0=AE=AA=E0=AE=BE=E0=AE=B3=E0=AF=88=E0=AE=AF=E0=AE=99=
=E0=AF=8D=E0=AE=95=E0=AF=8B=E0=AE=9F=E0=AF=8D=E0=AE=9F=E0=AF=88=E0=AE=AF=E0=
=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=A8=E0=AE=B5=E0=AE=AE=E0=AF=8D=E0=AE=AA=E0=
=AE=B0=E0=AF=8D&nbsp;15 - =E0=AE=86=E0=AE=AE=E0=AF=8D =E0=AE=A4=E0=AF=87=E0=
=AE=A4=E0=AE=BF (=E0=AE=9E=E0=AE=BE=E0=AE=AF=E0=AE=BF=E0=AE=B1=E0=AF=8D=E0=
=AE=B1=E0=AF=81=E0=AE=95=E0=AF=8D=E0=AE=95=E0=AE=BF=E0=AE=B4=E0=AE=AE=E0=AF=
=88) =E0=AE=A8=E0=AE=9F=E0=AF=88=E0=AE=AA=E0=AF=86=E0=AE=B1=E0=AF=81=E0=AE=
=95=E0=AE=BF=E0=AE=B1=E0=AE=A4=E0=AF=81.</DIV>
<DIV>&nbsp;</DIV>
<DIV>=E0=AE=AE=E0=AE=BF=E0=AE=95=E0=AE=95=E0=AF=8D =E0=AE=95=E0=AF=81=E0=AE=
=B1=E0=AF=88=E0=AE=A8=E0=AF=8D=E0=AE=A4 =E0=AE=8E=E0=AE=A3=E0=AF=8D=E0=AE=
=A3=E0=AE=BF=E0=AE=95=E0=AF=8D=E0=AE=95=E0=AF=88=E0=AE=AF=E0=AE=BF=E0=AE=B2=
=E0=AE=BE=E0=AE=A9 =E0=AE=A8=E0=AE=AA=E0=AE=B0=E0=AF=8D=E0=AE=95=E0=AE=B3=
=E0=AF=87&nbsp;=E0=AE=85=E0=AE=A9=E0=AF=81=E0=AE=AE=E0=AE=A4=E0=AE=BF=E0=AE=
=95=E0=AF=8D=E0=AE=95=E0=AE=AA=E0=AF=8D=E0=AE=AA=E0=AE=9F=E0=AF=81=E0=AE=95=
=E0=AE=BF=E0=AE=A9=E0=AF=8D=E0=AE=B1=E0=AE=A9=E0=AE=B0=E0=AF=8D. =E0=AE=95=
=E0=AE=B2=E0=AE=A8=E0=AF=8D=E0=AE=A4=E0=AF=81=E0=AE=95=E0=AF=8D =E0=AE=95=
=E0=AF=8A=E0=AE=B3=E0=AF=8D=E0=AE=B3 =E0=AE=B5=E0=AE=BF=E0=AE=B0=E0=AF=81=
=E0=AE=AE=E0=AF=8D=E0=AE=AA=E0=AF=81=E0=AE=B5=E0=AF=8B=E0=AE=B0=E0=AF=8D =
=E0=AE=AE=E0=AF=81=E0=AE=A9=E0=AF=8D=E0=AE=AA=E0=AE=A4=E0=AE=BF=E0=AE=B5=E0=
=AF=81 =E0=AE=9A=E0=AF=86=E0=AE=AF=E0=AF=8D=E0=AE=A4=E0=AF=81 =E0=AE=95=E0=
=AF=8A=E0=AE=B3=E0=AF=8D=E0=AE=B3=E0=AE=B5=E0=AF=81=E0=AE=AE=E0=AF=8D.</DIV=
>
<DIV>&nbsp;</DIV>
<DIV>=E0=AE=A4=E0=AF=8A=E0=AE=9F=E0=AE=B0=E0=AF=8D=E0=AE=AA=E0=AF=81=E0=AE=
=95=E0=AF=8D=E0=AE=95=E0=AF=81:</DIV>
<DIV>9487177604</DIV>
<DIV>9345545658</DIV></td></tr></table><br>



      <!--1--><hr size=3D"1"></hr>=20
The INTERNET now has a personality. YOURS! <a href=3D"http://in.rd.yahoo.co=
m/tagline_yyi_1/*http://in.yahoo.com/" target=3D"_blank">See your Yahoo! Ho=
mepage</a>.</p>

    </div>
=20=20=20=20=20

    <!--~-|**|PrettyHtmlStart|**|-~-->
    <div style=3D"color: #fff; height: 0;">__._,_.___</div>

=20=20=20=20=20=20=20=20
=20=20
=20=20=20
    <div id=3D"ygrp-actbar" style=3D"clear: both; margin-bottom: 10px; whit=
e-space: nowrap; color: #666; padding-top: 15px;">
      <div>
        <a href=3D"mailto:amudamtamil@yahoo.co.in?subject=3D=E0=AE=B5=E0=AE=
=BE=E0=AE=B4=E0=AF=8D=E0=AE=B5=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=AE=89=E0=AE=
=AF=E0=AE=B0=E0=AE=B2=E0=AE=BE=E0=AE=AE=E0=AF=8D...">
          Reply to <span style=3D"font-weight: 700;">sender</span></a>
          | <a href=3D"mailto:ponniyinselvan@yahoogroups.com?subject=3D=E0=
=AE=B5=E0=AE=BE=E0=AE=B4=E0=AF=8D=E0=AE=B5=E0=AE=BF=E0=AE=B2=E0=AF=8D =E0=
=AE=89=E0=AE=AF=E0=AE=B0=E0=AE=B2=E0=AE=BE=E0=AE=AE=E0=AF=8D...">
        Reply to <span style=3D"font-weight: 700;">group</span></a>
      </div>

                <a href=3D"http://groups.yahoo.com/group/ponniyinselvan/mes=
sage/35363;_ylc=3DX3oDMTM2cTVpdjJhBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ3Jwc=
3BJZAMxNzA1MDE5NTA5BG1zZ0lkAzM1MzYzBHNlYwNmdHIEc2xrA3Z0cGMEc3RpbWUDMTI1NzY4=
NzE1MQR0cGNJZAMzNTM2Mw--">Messages in this topic</a>
          (<span style=3D"font-weight: 700;">1</span>)
          </div>=20
<!------- Start Nav Bar ------>
<!-- |**|begin egp html banner|**| -->
<!-- |**|end egp html banner|**| -->

<!-- |**|begin egp html banner|**| -->
<div id=3D"ygrp-vital" style=3D"background-color: #e0ecee; font-family: Ver=
dana; font-size: 10px; margin-bottom: 10px; padding: 10px;">
      <span id=3D"vithd" style=3D"font-weight: bold; color: #333; text-tran=
sform: uppercase; ">Recent Activity:</span>

    <ul style=3D"list-style-type: none; margin: 0; padding: 0; display: inl=
ine;">
            <li style=3D"border-right: 1px solid #000; font-weight: 700; di=
splay: inline; padding: 0 5px; margin-left: 0;">
      <span class=3D"cat"><a href=3D"http://groups.yahoo.com/group/ponniyin=
selvan/members;_ylc=3DX3oDMTJmbXNzOHBwBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ=
3Jwc3BJZAMxNzA1MDE5NTA5BHNlYwN2dGwEc2xrA3ZtYnJzBHN0aW1lAzEyNTc2ODcxNTE-?o=
=3D6" style=3D"text-decoration: none;">New Members</a></span>
      <span class=3D"ct" style=3D"color: #ff7900;">17</span>
    </li>
                                      <li style=3D"border-right: 1px solid =
#000; font-weight: 700; display: inline; padding: 0 5px; margin-left: 0;">
      <span class=3D"cat"><a href=3D"http://groups.yahoo.com/group/ponniyin=
selvan/files;_ylc=3DX3oDMTJndnU5M2txBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ3J=
wc3BJZAMxNzA1MDE5NTA5BHNlYwN2dGwEc2xrA3ZmaWxlcwRzdGltZQMxMjU3Njg3MTUx" styl=
e=3D"text-decoration: none;">New Files</a></span>
      <span class=3D"ct" style=3D"color: #ff7900;">2</span>
    </li>
              </ul>
=20=20=20=20
  <div style=3D"clear: both; padding-top: 2px; color: #1e66ae;">
    <a href=3D"http://groups.yahoo.com/group/ponniyinselvan;_ylc=3DX3oDMTJl=
cXJyZWtrBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ3Jwc3BJZAMxNzA1MDE5NTA5BHNlYwN=
2dGwEc2xrA3ZnaHAEc3RpbWUDMTI1NzY4NzE1MQ--" style=3D"border-right: 1px solid=
 #000; padding-right: 5px; margin-right: 2px; text-decoration: none;">Visit=
 Your Group</a>
    <a href=3D"http://groups.yahoo.com/group/ponniyinselvan/post;_ylc=3DX3o=
DMTJlN2g1dDRoBF9TAzk3MzU5NzE0BGdycElkAzYyNDg5MzEEZ3Jwc3BJZAMxNzA1MDE5NTA5BH=
NlYwNmdHIEc2xrA250cGMEc3RpbWUDMTI1NzY4NzE1MQ--" style=3D"font-weight: 700; =
text-decoration: none;">Start a New Topic</a>
  </div>
</div>

        <div id=3D"ygrp-grft" style=3D"font-family: Verdana; font-size: 12p=
x; padding: 15px 0;">
=20=20=20=20=20=20
<!-- |**|begin egp html banner|**| -->

      ---------------------------------------------------------------------=
------<BR>
DISCLAIMER: The Founder / Convenor of the Group and / or its Moderators do =
<BR>
not subscribe to the views of the Members and subscriber alone is <BR>
responsible to defend the view of the subscriber if and when challenged by =
any person/s or Authority and/or by the process of Law.<BR>
<BR>
Members are requested to ensure that copyright issues are not violated<BR>
---------------------------------------------------------------------------=
-<BR>
Visit <a href=3D"http://ponniyinselvan.in">http://ponniyinselvan.in</a> to =
find archived messages<BR>
Visit <a href=3D"http://festival2009.ponniyinselvan.in">http://festival2009=
.ponniyinselvan.in</a> to find out about PSVP Vizha<BR>
---------------------------------------------------------------------------=
<BR>
=20=20=20=20=20=20
<!-- |**|end egp html banner|**| -->

    </div>
            <div id=3D"ygrp-mkp" style=3D"border: 1px solid #d8d8d8; clear:=
 both; float: left; font-family: Arial; margin: 5px 0 10px 0; padding: 0 10=
px;">
      <div id=3D"hd" style=3D"color: #628c2a; font-size: 85%; font-weight: =
700; line-height: 122%; margin: 10px 0;">MARKETPLACE</div>
      <div id=3D"ads" style=3D"margin-bottom: 10px;">
                  <div class=3D"ad" style=3D"color: #628C2A; font-family: A=
rial; font-weight: 700; padding: 0 0;">
            <a href=3D"http://us.ard.yahoo.com/SIG=3D14kkgkiv7/M=3D493064.1=
2016295.13793596.10835568/D=3Dgroups/S=3D1705019509:MKP1/Y=3DYAHOO/EXP=3D12=
57694351/L=3D/B=3DZf49TkPDhEA-/J=3D1257687151356346/K=3DOfEolhzMU6TKfqM5v6_=
13g/A=3D5697381/R=3D0/SIG=3D11eaa5dke/*http://groups.yahoo.com/group/mompow=
ergroup/">Mom Power: Discover the community of moms doing more for their fa=
milies, for the world and for each other</a>          </div>
                              </div>
    </div>
=20=20
<div id=3D"ft" style=3D"font-family: Arial; font-size: 11px; margin-top: 5p=
x; padding: 0 2px 0 0; clear: both;">
  <a href=3D"http://groups.yahoo.com/;_ylc=3DX3oDMTJkZ3Qzczg3BF9TAzk3NDc2NT=
kwBGdycElkAzYyNDg5MzEEZ3Jwc3BJZAMxNzA1MDE5NTA5BHNlYwNmdHIEc2xrA2dmcARzdGltZ=
QMxMjU3Njg3MTUx" style=3D"float: left;"><img src=3D"http://l.yimg.com/a/i/u=
s/yg/logo/us.gif" height=3D"15" width=3D"137" alt=3D"Yahoo! Groups" style=
=3D"border: 0;"/></a>
  <div style=3D"color: #747575; float: right;">Switch to: <a href=3D"mailto=
:ponniyinselvan-traditional@yahoogroups.com?subject=3DChange Delivery Forma=
t: Traditional" style=3D"text-decoration: none;">Text-Only</a>, <a href=3D"=
mailto:ponniyinselvan-digest@yahoogroups.com?subject=3DEmail Delivery: Dige=
st" class=3D"margin-rt" style=3D"text-decoration: none;">Daily Digest</a> &=
bull; <a href=3D"mailto:ponniyinselvan-unsubscribe@yahoogroups.com?subject=
=3DUnsubscribe" style=3D"text-decoration: none;">Unsubscribe</a> &bull; <a =
href=3D"http://docs.yahoo.com/info/terms/" style=3D"text-decoration: none;"=
>Terms of Use</a></div>
</div>

<!-- |**|end egp html banner|**| -->

  </div> <!-- ygrp-msg -->

  <!-- Sponsor -->
  <!-- |**|begin egp html banner|**| -->
  <div id=3D"ygrp-sponsor" style=3D"width:160px; float:right; clear:none; m=
argin:0 0 25px 0; background: #fff;">

<!-- Start Recommendations -->
<div id=3D"ygrp-reco">
     </div>
<!-- End Recommendations -->



  </div>   <!-- |**|end egp html banner|**| -->

  <div style=3D"clear:both; color: #FFF; font-size:1px;">.</div>
</div>

  <img src=3D"http://geo.yahoo.com/serv?s=3D97359714/grpId=3D6248931/grpspI=
d=3D1705019509/msgId=3D35363/stime=3D1257687151/nc1=3D4025304/nc2=3D5807837=
/nc3=3D5741391" width=3D"1" height=3D"1"> <br>

<div style=3D"color: #fff; height: 0;">__,_._,___</div>
<!--~-|**|PrettyHtmlEnd|**|-~-->

</body>

<!--~-|**|PrettyHtmlStart|**|-~-->
<head>
  <style type=3D"text/css">
  <!--
  #ygrp-mkp {
  border: 1px solid #d8d8d8;
  font-family: Arial;
  margin: 10px 0;
  padding: 0 10px;
}

#ygrp-mkp hr {
  border: 1px solid #d8d8d8;
}

#ygrp-mkp #hd {
  color: #628c2a;
  font-size: 85%;
  font-weight: 700;
  line-height: 122%;
  margin: 10px 0;
}

#ygrp-mkp #ads {
  margin-bottom: 10px;
}

#ygrp-mkp .ad {
  padding: 0 0;
}

#ygrp-mkp .ad a {
  color: #0000ff;
  text-decoration: none;
}
  #ygrp-sponsor #ygrp-lc {
  font-family: Arial;
}

#ygrp-sponsor #ygrp-lc #hd {
  margin: 10px 0px;
  font-weight: 700;
  font-size: 78%;
  line-height: 122%;
}

#ygrp-sponsor #ygrp-lc .ad {
  margin-bottom: 10px;
  padding: 0 0;
}

  a {
    color: #1e66ae;
  }

  #actions {
    font-family: Verdana;
    font-size: 11px;
    padding: 10px 0;
  }

  #activity {
    background-color: #e0ecee;
    float: left;
    font-family: Verdana;
    font-size: 10px;
    padding: 10px;
  }

  #activity span {
    font-weight: 700;
  }

  #activity span:first-child {
    text-transform: uppercase;
  }

  #activity span a {
    color: #5085b6;
    text-decoration: none;
  }

  #activity span span {
    color: #ff7900;
  }

  #activity span .underline {
    text-decoration: underline;
  }

  .attach {
    clear: both;
    display: table;
    font-family: Arial;
    font-size: 12px;
    padding: 10px 0;
    width: 400px;
  }

  .attach div a {
    text-decoration: none;
  }

  .attach img {
    border: none;
    padding-right: 5px;
  }

  .attach label {
    display: block;
    margin-bottom: 5px;
  }

  .attach label a {
    text-decoration: none;
  }
=20=20
  blockquote {
    margin: 0 0 0 4px;
  }

  .bold {
    font-family: Arial;
    font-size: 13px;
    font-weight: 700;
  }

  .bold a {
    text-decoration: none;
  }

  dd.last p a {
    font-family: Verdana;
    font-weight: 700;
  }

  dd.last p span {
    margin-right: 10px;
    font-family: Verdana;
    font-weight: 700;
  }

  dd.last p span.yshortcuts {
    margin-right: 0;
  }

  div.attach-table div div a {
    text-decoration: none;
  }

  div.attach-table {
    width: 400px;
  }

  div.file-title a, div.file-title a:active, div.file-title a:hover, div.fi=
le-title a:visited {
    text-decoration: none;
  }

  div.photo-title a, div.photo-title a:active, div.photo-title a:hover, div=
.photo-title a:visited {
    text-decoration: none;
  }

  div#ygrp-mlmsg #ygrp-msg p a span.yshortcuts {
    font-family: Verdana;
    font-size: 10px;
    font-weight: normal;
  }

  .green {
    color: #628c2a;
  }

  .MsoNormal {
    margin: 0 0 0 0;
  }

  o {
    font-size: 0;
  }

  #photos div {
    float: left;
    width: 72px;
  }

  #photos div div {
    border: 1px solid #666666;
    height: 62px;
    overflow: hidden;
    width: 62px;
  }

  #photos div label {
    color: #666666;
    font-size: 10px;
    overflow: hidden;
    text-align: center;
    white-space: nowrap;
    width: 64px;
  }

  #reco-category {
    font-size: 77%;
  }

  #reco-desc {
    font-size: 77%;
  }

  .replbq {
    margin: 4px;
  }

  #ygrp-actbar div a:first-child {
   /* border-right: 0px solid #000;*/
    margin-right: 2px;
    padding-right: 5px;
  }

  #ygrp-mlmsg {
    font-size: 13px;
    font-family: Arial, helvetica,clean, sans-serif;
    *font-size: small;
    *font: x-small;
  }

  #ygrp-mlmsg table {
    font-size: inherit;
    font: 100%;
  }

  #ygrp-mlmsg select, input, textarea {
    font: 99% Arial, Helvetica, clean, sans-serif;
  }

  #ygrp-mlmsg pre, code {
    font:115% monospace;
    *font-size:100%;
  }

  #ygrp-mlmsg * {
    line-height: 1.22em;
  }

  #ygrp-mlmsg #logo {
    padding-bottom: 10px;
  }

  #ygrp-mlmsg a {
    color: #1E66AE;
  }

  #ygrp-msg p a {
    font-family: Verdana;
  }

  #ygrp-msg p#attach-count span {
    color: #1E66AE;
    font-weight: 700;
  }

  #ygrp-reco #reco-head {
    color: #ff7900;
    font-weight: 700;
  }

  #ygrp-reco {
    margin-bottom: 20px;
    padding: 0px;
  }

  #ygrp-sponsor #ov li a {
    font-size: 130%;
    text-decoration: none;
  }

  #ygrp-sponsor #ov li {
    font-size: 77%;
    list-style-type: square;
    padding: 6px 0;
  }=20

  #ygrp-sponsor #ov ul {
    margin: 0;
    padding: 0 0 0 8px;
  }

  #ygrp-text {
    font-family: Georgia;
  }

  #ygrp-text p {
    margin: 0 0 1em 0;
  }

  #ygrp-text tt {
    font-size: 120%;
  }

  #ygrp-vital ul li:last-child {
    border-right: none !important;=20
  }=20
  -->
  </style>
</head>

<!--~-|**|PrettyHtmlEnd|**|-~-->
</html>
<!-- end group email -->


--0-2119700399-1257687071=:31204--