From anandc272@yahoo.com Mon May 27 10:16:40 2002
Return-Path: <anandc272@yahoo.com>
X-Sender: anandc272@yahoo.com
X-Apparently-To: ponniyinselvan@yahoogroups.com
Received: (EGP: mail-8_0_3_2); 27 May 2002 17:16:39 -0000
Received: (qmail 50159 invoked from network); 27 May 2002 17:16:38 -0000
Received: from unknown (66.218.66.218)
  by m1.grp.scd.yahoo.com with QMQP; 27 May 2002 17:16:38 -0000
Received: from unknown (HELO web14104.mail.yahoo.com) (216.136.172.134)
  by mta3.grp.scd.yahoo.com with SMTP; 27 May 2002 17:16:38 -0000
Message-ID: <20020527171638.6848.qmail@web14104.mail.yahoo.com>
Received: from [203.199.245.199] by web14104.mail.yahoo.com via HTTP; Mon, 27 May 2002 10:16:38 PDT
Date: Mon, 27 May 2002 10:16:38 -0700 (PDT)
Subject: Characters
To: ponniyinselvan@yahoogroups.com
In-Reply-To: <1022499915.353.87162.m12@yahoogroups.com>
MIME-Version: 1.0
Content-Type: multipart/alternative; boundary="0-1622833-1022519798=:6843"
From: Anand Kumar <anandc272@yahoo.com>
X-Yahoo-Group-Post: member; u=70049721
X-Yahoo-Profile: anandc272
X-Archive-Message-Key: 34
X-Archived-By: http://thiru.in/archive
X-Archive-On: Fri, 14 Jan 2011 00:55:44 +0000

           
--0-1622833-1022519798=:6843 
Content-Type: text/plain; charset=us-ascii


hi everybody,

             in my view, nandini should be played by a person who should be arrogantly beautiful, should have a nice smile with a little bit of sorrow in her face but should be able to practise routhram well. so, i dont think any actress now has these qualities. 

           What abt vandhiya devan? He should be humorous, twinkling eyes, but at the the same time should be brave. So whats your choice?

 



Bye



"Truly great friends are hard to find, difficult to leave, and impossible to forget."



---------------------------------
Do You Yahoo!?
Yahoo! - Official partner of 2002 FIFA World Cup           
--0-1622833-1022519798=:6843 
Content-Type: text/html; charset=us-ascii

<P>hi everybody,</P>
<P>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; in my view, nandini should be played by a person who should be arrogantly beautiful, should have a nice smile with a little bit of sorrow in her face but should be able to practise routhram well. so, i dont think any actress now has these qualities. </P>
<P>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; What abt vandhiya devan? He should be humorous, twinkling eyes, but at the the same time should be brave. So whats your choice?</P>
<P>&nbsp;</P><BR><BR><P>Bye<IMG src="http://us.i1.yimg.com/us.yimg.com/i/mesg/tsmileys/j.gif"></P>
<P><FONT face=arial size=-1><B><A href="http://www.geocities.com/anandc272/sign.bmp"><IMG align=baseline alt=Anand border=0 hspace=0 src="http://www.geocities.com/anandc272/sign.bmp" style="HEIGHT: 59px; WIDTH: 187px"></A></B></FONT></P>
<P>"Truly great friends are hard to find, difficult to leave, and impossible to forget."</P><p><br><hr size=1><b>Do You Yahoo!?</b><br>
<a href="http://rd.yahoo.com/welcome/*http://fifaworldcup.yahoo.com">Yahoo!</a> - Official partner of 2002 FIFA World Cup           
--0-1622833-1022519798=:6843--