From sampath_srinivasaraghavan@yahoo.co.in Fri Nov 06 03:34:50 2009
Return-Path: <sampath_srinivasaraghavan@yahoo.co.in>
X-Sender: sampath_srinivasaraghavan@yahoo.co.in
X-Apparently-To: ponniyinselvan@yahoogroups.com
X-Received: (qmail 60365 invoked from network); 6 Nov 2009 11:34:49 -0000
X-Received: from unknown (98.137.34.44)
  by m1.grp.sp2.yahoo.com with QMQP; 6 Nov 2009 11:34:49 -0000
X-Received: from unknown (HELO n38b.bullet.mail.sp1.yahoo.com) (66.163.168.152)
  by mta1.grp.sp2.yahoo.com with SMTP; 6 Nov 2009 11:34:49 -0000
X-Received: from [69.147.65.174] by n38.bullet.mail.sp1.yahoo.com with NNFMP; 06 Nov 2009 11:34:35 -0000
X-Received: from [98.137.34.72] by t12.bullet.mail.sp1.yahoo.com with NNFMP; 06 Nov 2009 11:34:35 -0000
Date: Fri, 06 Nov 2009 11:34:35 -0000
To: ponniyinselvan@yahoogroups.com
Message-ID: <hd11kb+r45o@eGroups.com>
In-Reply-To: <96ab1a490911052247m40758d27na483c2a3f8e97959@mail.gmail.com>
User-Agent: eGroups-EW/0.82
MIME-Version: 1.0
Content-Type: text/plain; charset="ISO-8859-1"
Content-Transfer-Encoding: base64
X-Mailer: Yahoo Groups Message Poster
X-Yahoo-Newman-Property: groups-compose
X-Originating-IP: 66.163.168.152
X-eGroups-Msg-Info: 1:6:0:0:0
X-Yahoo-Post-IP: 115.109.15.87
From: "ssampath108" <sampath_srinivasaraghavan@yahoo.co.in>
Subject: =?iso-8859-1?B?UmU6IEZ3ZDogW1BvZXRyeSBJbiBTdG9uZXzgrpXg?=
 =?iso-8859-1?B?rrLgr43grrLgrr/grrLgr4cg4K6V4K6y4K+I4K61?=
 =?iso-8859-1?B?4K6j4K+N4K6j4K6u4K+NIOCuleCuo+CvjeCun+Cv?=
 =?iso-8859-1?B?i+CuruCvjV0gVGhlIG1vYXQgYXJvdW5kIHRoZSBU?=
 =?iso-8859-1?B?YW5qb3JlIEJpZyB0ZW1wbGUgfCDgrqTgrp7gr43g?=
 =?iso-8859-1?B?rprgr4gg4K6q4K+G4K6w4K6/4K6vIOCuleCvi+Cu?=
 =?iso-8859-1?B?r+Cuv+CusuCvjSDgroXgrpXgrrTgrr8=?=
X-Yahoo-Group-Post: member; u=216892431; y=y6KX5GiGLGuc88RHYX_TE0QE4_oaug50uWFw_hJb8oCtxfe66-oao2POdX0aXqXUflR6-g
X-Yahoo-Profile: ssampath108
X-Archive-Message-Key: 35340
X-Archived-By: http://thiru.in/archive
X-Archive-On: Wed, 19 Jan 2011 21:18:39 +0000

SGkgVmlqYXksCgpOaWNlIGFuZCBpbnRlcmVzdGluZy4gWW91IGhhdmUgYSBzaGFycCBleWUg
Zm9yIGRldGFpbHMgYW5kIG15c3Rlcmllcy4KUGVyaGFwcywgZHVyaW5nIHJlbm92YXRpb24g
aW4gdGhlIDIwdGggY2VudHVyeSwgdGhlIHNjdWxwdHVyZSB3YXMKcmVtb3ZlZCBhbmQgdGhl
biBmb3Jnb3R0ZW4uIExldCB1cyBob3BlIGl0IGlzIHNhZmUgaW4gYSBtdXNldW0uCgpJIGhh
dmUgYSBkb3VidC4gTm9ybWFsbHksIG9ubHkgZm9ydHMgYW5kIHBhbGFjZXMgaGF2ZSBtb2F0
cyBhcyBhIGJhcnJpZXIKYWdhaW5zdCBhdHRhY2tzLiBXaHkgZm9yIGEgdGVtcGxlPyBBcmUg
dGhlcmUgb3RoZXIgdGVtcGxlcyB3aXRoIG1vdHM/IEkKYW0gbm90IGF3YXJlIG9mIGFueS4K
U2FtcGF0aAoKCi0tLSBJbiBwb25uaXlpbnNlbHZhbkB5YWhvb2dyb3Vwcy5jb20sIHZqIGt1
bWFyIDx2ai5lcGlzdGVtZUAuLi4+IHdyb3RlOgo+Cj4gUG9ldHJ5IEluIFN0b25lfOCuleCu
suCvjeCusuCuv+CusuCvhwrgrpXgrrLgr4jgrrXgrqPgr43grqPgrq7gr40KPiDgrpXgrqPg
r43grp/gr4vgrq7gr40gaGFzIHBvc3RlZCBhIG5ldyBpdGVtLCAnVGhlIG1vYXQgYXJvdW5k
CnRoZSBUYW5qb3JlIEJpZwo+IHRlbXBsZSB8IOCupOCunuCvjeCumuCviCDgrqrgr4bgrrDg
rr/grq8K4K6V4K+L4K6v4K6/4K6y4K+NIOCuheCuleCutOCuvyAnCj4KPiBbbGFuZ19lbl0K
Pgo+IFRoZSByZWNlbnQgaGVhZGxpbmVzIGZvciByZW5vdmF0aW9uIG9mIHRoZSBtb2F0IGFy
b3VuZCB0aGUgQmlnIHRlbXBsZQppbgo+IHRhbmpvcmUsCj4gQVNJIHN1Ym1pdHMgUnMuMS1j
cm9yZSBwcm9wb3NhbCB0byByZW5vdmF0ZSBtb2F0IGFyb3VuZCBCaWcgVGVtcGxlICwKdG9v
ayBtZQo+IGJhY2sgc29tZSB5ZWFycyBhZ28gLSB3aGVuIGkgaGFkIGNoYW5jZWQgb24gYSB2
ZXJ5IGludGVyZXN0aW5nIGFudGlxdWUKPiBwaG90b2dyYXBoIGZyb20gdGhlIGFyY2hpdmVz
IG9mIHRoZSBCcml0aXNoIExpYnJhcnkuCj4KPiBUaGUgYXJjaGl2ZXMgYXJlIGEgcmVhbCB0
cmVhc3VyZSBbLi4uXQo+Cj4gWW91IG1heSB2aWV3IHRoZSBsYXRlc3QgcG9zdCBhdAo+Cmh0
dHA6Ly93d3cucG9ldHJ5aW5zdG9uZS5pbi8yMDA5LzExLzA2L3RoZS1tb2F0LWFyb3VuZC10
aGUtdGFuam9yZS1iaWctdFwKZW1wbGUuaHRtbAo+Cj4g4K6k4K6e4K+N4K6a4K+IIOCuquCv
huCusOCuv+CuryDgrpXgr4vgrq/grr/grrLgr40KPgrgroXgrpXgrrTgrr88aHR0cDovL3d3
dy5wb2V0cnlpbnN0b25lLmluL2xhbmcvdGEvMjAwOS8xMS8wNi90aGUtbW9hXAp0LWFyb3Vu
ZC10aGUtdGFuam9yZS1iaWctdGVtcGxlLmh0bWw+Cj4KPiA8aHR0cDovL3d3dy5wb2V0cnlp
bnN0b25lLmluL3dwLWFkbWluL3Bvc3QucGhwP2FjdGlvbj1lZGl0JnBvc3Q9MjcyMD4KPgo+
IOCumuCuruCvgOCuquCupOCvjeCupOCuv+Curwrgrqjgrr7grrPgr4fgrp/gr43grp/grr/g
rrLgr40g4K6k4K+K4K6y4K+N4K6y4K6/4K6v4K6y4K+NCuCupOCvgeCuseCviCDgrifgrrDg
r4Eg4K6V4K+L4K6f4K6/CuCusOCvgeCuquCuvuCur+CvjSDgrprgr4bgrrLgrrXgrr/grrLg
r40K4K6k4K6e4K+N4K6a4K+IIOCuquCvhuCusOCuv+Curwo+IOCuleCvi+Cur+Cuv+CusuCv
jSDgroXgrpXgrrTgrr/grq/gr4gK4K6a4K+G4K6q4K+N4K6q4K6p4K6/4K6f4K6q4K+NIOCu
quCvi+CuleCuv+CuseCupOCvgQrgro7grqngr43grrEg4K6a4K+G4K6v4K+N4K6k4K6/CuCu
teCuvuCumuCuv+CupOCvjeCupOCvgSDgrq7grpXgrr/grrTgr43grqjgr43grqTgr4fgrqng
r40KPgrgrprgr4bgrq/gr43grqTgrr88aHR0cDovL3d3dy5oaW5kdS5jb20vMjAwOS8xMS8w
NS9zdG9yaWVzLzIwMDkxMTBcCjU1ODEyMDEwMC5odG0+LuCuieCun+CuqeCvhwo+IOCuqOCu
v+CuqeCviOCuteCvgSDgrprgrr/grrIK4K6G4K6j4K+N4K6f4K+B4K6V4K6z4K+B4K6V4K+N
4K6V4K+BCuCuruCvgeCuqeCvjeCuqeCusOCvjSDgrqrgrr/grrDgrr/grp/gr43grp/grr/g
rrfgr40K4K6V4K6w4K+B4K614K+C4K6y4K6k4K+N4K6k4K6/4K6y4K+NIOCuieCus+CvjeCu
swrgrprgrr/grrIg4K6u4K6/4K6VIOCuheCusOCuv+Curwo+IOCuquCvgeCuleCviOCuquCv
jeCuquCun+CumeCvjeCuleCus+CviOCuquCvjQrgrqrgrr7grrDgr43grrXgr4jgrq/grr/g
rp/gr43grp/grqTgr4Hgrq7gr40uCuCuheCupOCuv+CusuCvgeCuruCvjQrgrpXgr4HgrrHg
rr/grqrgr43grqrgrr/grp/gr4Hgrq7gr40g4K6q4K6f4K6/4K6v4K6+4K6VCuCuJ+CusOCv
gSDgrqrgrp/grq7gr4Hgrq7gr40hISEKPgo+Cj4KaHR0cDovL3d3dy5wb2V0cnlpbnN0b25l
LmluL2xhbmcvdGEvMjAwOS8xMS8wNi90aGUtbW9hdC1hcm91bmQtdGhlLXRhbmpvXApyZS1i
aWctdGVtcGxlLmh0bWwKPgo+Cj4gQmVzdCByZWdhcmRzLAo+IFZpamF5Cj4gdmouZXBpc3Rl
bWVALi4uCj4K