From ramchi412@yahoo.com Wed Mar 20 17:27:28 2002
Return-Path: <ramchi412@yahoo.com>
X-Sender: ramchi412@yahoo.com
X-Apparently-To: ponniyinselvan@yahoogroups.com
Received: (EGP: unknown); 21 Mar 2002 01:26:50 -0000
Received: (qmail 95014 invoked from network); 21 Mar 2002 01:19:38 -0000
Received: from unknown (66.218.66.216)
  by m11.grp.scd.yahoo.com with QMQP; 21 Mar 2002 01:19:38 -0000
Received: from unknown (HELO n2.grp.scd.yahoo.com) (66.218.66.75)
  by mta1.grp.scd.yahoo.com with SMTP; 21 Mar 2002 01:19:38 -0000
Received: from [66.218.67.155] by n2.grp.scd.yahoo.com with NNFMP; 21 Mar 2002 01:19:38 -0000
Date: Thu, 21 Mar 2002 01:19:35 -0000
To: ponniyinselvan@yahoogroups.com
Subject: hai
Message-ID: <a7bcf7+oqkn@eGroups.com>
User-Agent: eGroups-EW/0.82
MIME-Version: 1.0
Content-Type: text/plain; charset=ISO-8859-1
Content-Length: 931
X-Mailer: Yahoo Groups Message Poster
From: "ramchi412" <ramchi412@yahoo.com>
X-Originating-IP: 134.121.73.57
X-Yahoo-Group-Post: member; u=73536123
X-Yahoo-Profile: ramchi412
X-Archive-Message-Key: 1
X-Archived-By: http://thiru.in/archive
X-Archive-On: Fri, 14 Jan 2011 00:54:53 +0000

I have read ponniyin selvan quite a few times but I think Kalki has
confused a bit.......probably sliped a bit when he was walking 
between the thin line of reality and Imagination.......
In one perspective we can conclude that
Nandini's father is the Pandiya king who  took Oomai
raani with him when she as unconcious...the pandia king who died 
in the battle with Karikalan is his son....so nandini is his 
sister...
In another perspective.......
i gathered that nandini and mathurandakan were born to oomai rani, 
but still it is not clear about who their father. most 
presumably
it was Pandiya king. but then again kalki raises a doubt because 
"how can nandini refer to her father as her lover" and in her 
hallucinations, nandini refers to the pandiya king as 
"anbe"........
Not only me lot many people in the world are confused abt. 
If someone could throw some light on this I would be grateful.
endrendrum anbudan,
Ram